haskell/ghcide

- .ghci
This file got removed when the project got renamed from hie-core to ghcide, before it got transferred to this repo. I find this file useful for invoking ghcid on ghcide, and also directly running ghci.
> Add a .ghci file

- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
The suggestions are extracted from GHC's error messages.
To make parsing these error messages easier, we set the flag
useUnicode=True, which makes GHC always use “smart quotes”.
(This is a port of the pull request https://github.com/digital-asset/daml/pull/2809 to the new repo.)
> Add code action for fixing misspelled variable names

- src/Development/IDE/GHC/Warnings.hs
- test/exe/Main.hs
Because we are constructing the message objects ourselves, as opposed to error messages which are constructed by GHC, we need to take care to respect the passed-in `PprStyle`.
This should fix the problems @jacg was seeing in #47 (though I haven't double-checked with his specific code).
> Make sure warnings use unqualified names where appropriate

- README.md
- extension/package-lock.json
- extension/package.json
The vscode library is deprecated in favor of @types/vscode.
See https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
This also add vsce as a devDependency, so you don't need to install
it globally. Instead you can run it via npm run vscepackage. This
simplifies the README (or future "hacking" instructions when the
extension is published)
> migrate to new @types/vscode, add vsce devDependency

- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
Code action for fixing misspelt module names in imports. The suggestions are those proposed by GHC.
> Code action for 'module not found'

- README.md
These options don‘t work with ghcide as far as I can tell. I believe they stem from copying the config used for hie-wrapper. As ghcide does not support hlint yet I believe this infos to be misleading. That‘s why I suggest deleting it.
> Delete non-ghcide options from coc.nvim example

- azure-pipelines.yml
- ghcide.cabal
- include/ghc-api-version.h
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/GHC/CPP.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/Import/FindImports.hs
- src/Development/IDE/Spans/Calculate.hs
- stack-ghc-lib.yaml
Previously we had a mix of GHC_STABLE and checks on
`__GLASGOW_HASKELL__`. This PR changes this to always check on
MIN_GHC_API_VERSION. Depending on whether you use ghc-lib or not (now
controlled by a cabal flag), this macro expands to MIN_VERSION_ghc or
MIN_VERSION_ghc_lib.
> Cleanup GHC API version checks

- .hlint.yaml
- ghcide.cabal
- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
Add code actions which replace typed holes, using GHC's "Relevant bindings include" hints.
> Code actions for filling typed holes

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Warnings.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
At present, all sorts of useful IDE featrues, such as diagnostics reporting and go-to-definition, stop working at the first sign of a type error. This PR attempts to fix this. The plan is:
+ defer type errors
+ report them as warnings during typechecking
+ re-upgrade them to errors after type checking
TODO:
> Defer type errors

- .ghci
- hie.yaml
Before `stack run ghcide` reported that about half the ghcide files couldn't load. Now it reports only 2 can't load, which is what it's always been. Also fixes the `ghcid` experience.
I suspect we should probably have a test that `ghcide` works on `ghcide` itself, but it doesn't completely work because its multiple components etc so I've no real idea what to do.
> Add -Iinclude where it's needed

- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
Will need more thorough testing, and maybe more discussion of the different approaches considered in #77.
> Add code actions for missing type signatures

- exe/Arguments.hs
- exe/Main.hs
> Add --version CLI option

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/GHC/Util.hs
This only matters for the DAML codebase (so I’ll add a test on that
side) where we use relative paths:
Previously, we would produce the include dir "." for moduleImportPath
"./A.daml"
and "" for moduleImportPath "./A/B.daml". This resulted in us ending
up with ./A.daml and A.daml in the Shake graph which resulted in
issues like https://github.com/digital-asset/daml/issues/2929.
We should move this logic completely over to the DAML repo at some
point but I’ll leave that for a separate PR.
> Use a consistent include dir for cwd

- ghcide.cabal
Stack warns about misplaced home modules
> Add Paths_ghcide, fixes a warning

- azure-pipelines.yml
- src/Development/IDE/Core/Rules.hs
Warnings are bad. Delete the 3 that got introduced, then fix the Azure pipelines, which was previously checking that the dependencies had no warnings (don't care), but not that the build had no errors (care a lot).
> No warnings

- src/Development/IDE/Core/Compile.hs
- test/exe/Main.hs
The text of the error messages of deferred type errors / typed holes / out of scope variables, refer to them as warnings, even after they have been upgraded back to errors. This PR fixes these messages.
> Fix deferred messages

- ghcide.cabal
We are coupled very tightly to the hie-bios API, and I'm sure 0.3 will break us, so put in a preemptive upper bound. I suggest going forward we always constrain ourselves to a specific hie-bios given the close coupling.
CC @mpickering
> Add an upper bound to hie-bios

- extension/package.json
That’s the publisher we use for uploading the DAML extension and it
makes little sense to have two publishers.
> Update extension metadata

- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/Rules.hs
- test/exe/Main.hs
Each file looks up its `hie.yaml` separately, and if they match, they share the same `hie.yaml`. I encountered a few bugs around the place on the way here, links to the upstream issues included.
I also rewrote the user setup/debug logic for `ghcide` on its own, to be based around the idea that a directory may have multiple hie.yaml files, and also to print out less stuff that might confuse users.
> Support multiple hie.yaml files

- exe/Main.hs
See #137 where it wasn't clear because the list of failing files pushed them off the edge.
> #137, make the status message clearer about what worked and what didn't

- ghcide.cabal
- test/exe/Main.hs
These tests document what works or doesn't work in terms of hover and find definition. Tests corresponding to features which do not work are marked as expected to fail, allowing the test suite as a whole to pass.
The current state of play is:
| | find definition | hover |
|-------------|-----------|---------|
| field in record definition | :heavy_check_mark:  | :heavy_check_mark: |
| field in record construction | :exclamation:  | :exclamation: |
| field name as accessor | :heavy_check_mark: | :heavy_check_mark: |
| top level name | :heavy_check_mark: | :heavy_check_mark: |
| record data constructor | :exclamation: | :exclamation:  |
| plain data constructor | :heavy_check_mark: | :heavy_check_mark:  |
| type constructor | :heavy_check_mark: | :exclamation: |
| plain parameter | …
> Add tests for find-definition and hover

- test/exe/Main.hs
These tests document and monitor the evolution of the capabilities
announced by the server in the initialize response.
Currently the server advertises almost no capabilities. Out of 23
top-level categories, the only 3 which are announced are
+ text document sync
+ hover
+ goto definition
At the very least code actions are known to be provided, but are not
announced in the initialize response.
Closes #105
> Initialize-response tests

- test/exe/Main.hs
A while ago, `testSession` was modified to include a 0.5s wait, for
the sake of tests which were looking for a specific and complete set
of diagnostics, in order to ensure that all the incoming diagnostics
had been received before the comparison was made. This made sense at a
time when the vast majority of tests fit this pattern. Today we have
plenty of tests which have no need for this. Hence:
+ `testSession` has been renamed to `testSessionWait`
+ a new `testSession` has been added, which does not wait at all
+ all tests which use `expectDiagnostics` have been modified to use
`testSessionWait`, all other tests use the new delayless
`testSession`.
Locally this knocks almost 25% off the runtime of the full test
suite.
> Stop waiting in tests which don't need to

- azure-pipelines.yml
- src/Development/IDE/Core/Compile.hs
On a large DAML project, we occasionally saw error about missing
modules during typechecking during concurrent compilations. This was
caused by the fact that we modified the IORef in the HscEnv which is
shared between concurrent compilations.
> Use a separate finder cache for each typecheck call

- stack88.yaml
Still not at a point where all our deps are back in stackage but we’re
getting closer.
> Bump GHC 8.8 stacksnapshot

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Util.hs
- test/exe/Main.hs
This fixes some issues where we used an uppercase drive letter in the
import path even though the LSP client uses lowercase drive letters
> Avoid file path normalization in moduleImportPath

- exe/Main.hs
Experience shows (e.g. #160) that people sometimes mistakenly start `ghcide` on
the command line with the `--lsp` option (which is intended to be used
only in server/client communication scenarios) and then wonder why
nothing is working..
So let's issue a warning message whenever `--lsp` is used.
> Issue visual warning for humans if --lsp option used

- docs/Setup.md
> Copy the content of #159 to the setup guide

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/GHC/Error.hs
- src/Development/IDE/Import/FindImports.hs
- src/Development/IDE/Types/Options.hs
ghcide allows users to define custom preprocessors of the parsed source tree emitted by GHC. So far these could modify the source tree and emit additional errors, but could not emit additional warnings. This allows preprocessors to emit additional warnings as well. This change is motivated by https://github.com/digital-asset/daml/pull/3228.
- Defines `IdePreprocessedSource` which captures the preprocessed `GHC.ParsedSource` and errors and warnings emitted by the preprocessor.
- Changes the preprocessor type to return `IdePreprocessedSource`.
- Preprocessor warnings are appended to the list of warnings generated by GHC's own parser.
- Preprocessor warnings do not raise an error in `parseFileContents`.
> Allow preprocessors to emit warnings

- test/exe/Main.hs
Adds another row (*external value*) to the *find definition* / *hover* test matrix: leaving it looking like this:
| | find definition | hover |
|-------------|-----------|---------|
| field in record definition | :heavy_check_mark:  | :heavy_check_mark: |
| field in record construction | :x:  | :x: |
| field name as accessor | :heavy_check_mark: | :heavy_check_mark: |
| top level name | :heavy_check_mark: | :heavy_check_mark: |
| record data constructor | :x: | :x: |
| plain data constructor | :heavy_check_mark: | :heavy_check_mark:  |
| type constructor | :heavy_check_mark: | :x: |
| external type constructor | :x: | :x: |
| external value | :x: | :heavy_check_mark: |
| plain parameter | :heavy_check_mark: | :heavy_check_mark: |
| pattern match name | :heavy_check_mark: | …
> Add gotoDef/hover tests for values from other package

- ghcide.cabal
- src/Development/IDE/GHC/Util.hs
- test/data/GotoHover.hs
- test/exe/Main.hs
This has been written on top of #168 which has not been merged yet: only the last 2 commits belong to this PR.
The sample code used in the goto def / hover tests, is becoming to unwieldy to be kept in strings in the test sources. So it has been moved out into a separate file in a new directory `test/data`.
> Move test sample code out to external file

- test/data/GotoHover.hs
- test/exe/Main.hs
+ internal class in instance declaration
+ internal class in type signature
+ external class in type signature
Hover seems not to work for classes at all.
Goto def works for internal classes, but not external ones.
This leaves the table looking like this:
| | find definition | hover |
|-------------|-----------|---------|
| field in record definition | :heavy_check_mark:  | :heavy_check_mark: |
| field in record construction | :x:  | :x: |
| field name as accessor | :heavy_check_mark: | :heavy_check_mark: |
| top level name | :heavy_check_mark: | :heavy_check_mark: |
| record data constructor | :x: | :x: |
| plain data constructor | :heavy_check_mark: | :heavy_check_mark:  |
| type constructor | :heavy_check_mark: | :x: |
| external type constructor | :x: | :x: |
| external value | :x: | …
> Add goto def / hover tests for classes

- src/Development/IDE/Core/Rules.hs
use the `IdeResult` type synonym in the new `generateCore` function's return
type instead of effectively inlining it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/digital-asset/ghcide/180)
> Use IdeResult in generateCore

- src/Development/IDE/Types/Logger.hs
This is for logging telemetry events in the DAML IDE. Note that this does not enable telemetry for ghcide in general.
> New logging priority for telemetry events

- ghcide.cabal
- src/Development/IDE/Core/Compile.hs
- test/exe/Main.hs
Call initializePlugins before running typecheck.
> Support plugins

- README.md
We never supported this and still don’t so for now let’s remove it.
> Remove organize imports from the supported features

- README.md
(according to https://github.com/joaotavora/eglot#1-2-3)
> Clarify that eglot requires Emacs 26.1+

- exe/Main.hs
Not sure why sometimes the path to the cradle is absolute and other times it's relative. Using Linux and direct cradles, happens both on Emacs and Code. 
Because of this issue, ghcide v0.4 is broken for me on certain files both on personal projects and at work.
> Fix horrible path normalisation issue

- ghcide.cabal
- src/Development/IDE/LSP/CodeAction.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Server.hs
- test/exe/Main.hs
This PR adds code lenses for missing type signatures, as discussed in #88. Missing type signatures appear as comments on top of the start of the definition, as shown in [this image](https://imgur.com/a/KcQpagl). When the user clicks on the definition, it's added to the source code.
Unfortunately, the [specification of code lenses](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_codeLens) is not as straightforward as code actions. Instead of returning how to edit the file directly, we need to return an identifier with a command, which is then called when the user clicks on the code lens. That command does not return what to do either, instead it may request things from the client by using a server request. Hence the need for a new type …
> Code lens for missing signatures

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Orphans.hs
- src/Development/IDE/GHC/Util.hs
- test/exe/Main.hs
This is a first attempt to fix #34. Right now, things seem to work fine, at least examples do! :)
There are a few things that might need additional attention:
- Right now all modules are compiled to bytecode, because they might be needed in the future. Could we be more precise on this, to avoid having to generate all that code?
- When a file is read by TemplateHaskell, it assumes that the current directory is the one in which `ghcide` is run. This is different from what Stack or Cabal do, because they assume the `hs-source-dirs` of the project is the current directory. This means files cannot be loaded correctly by TemplateHaskell splices in `ghcide`.
> Support TemplateHaskell

- src/Development/IDE/Core/Shake.hs
If you do, then VS Code keeps restarting the spinner, and it looks a bit epileptic inducing.
> Don't repeatedly update the progress

- exe/Main.hs
It'd be useful for scripting or integration tests.
> Indicate failures with exit code in command-line mode.

- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/LSP/LanguageServer.hs
We have seen a bunch of failures on CI where this failed with
EBUSY. I find the hDuplicateTo here to be quite useful for debugging
since you don’t have to worry about corrupting the JSON-RPC stream to
instead of getting rid of it, we add a somewhat ugly workaround.
There is an explanation in an inline comment on why this helps but
admittedly I am somewhat guessing since I don’t understand what is
actually allocating the file descriptor that turns out to be
stdout. That said, I am not guessing on the results: Without this PR I
am able to make this fail in roughly 50% of the cases on CI whereas
with this PR, I’ve now run it 60 times on CI without a single failure.
> Workaround hDuplicateTo issues

- src/Development/IDE/Spans/Type.hs
This helped with debugging #237, so maybe it's worth keeping.
> Cleaner Show instance for SpanInfo

- test/data/GotoHover.hs
- test/exe/Main.hs
Hover and goto definition only work on the function name in the first clause of
a function being defined with multiple equation clauses.
Here are some tests that document this.
> Add tests for #246

- test/data/GotoHover.hs
- test/exe/Main.hs
A number of tests are currently passing as expected failures. These tests exist to document known issues. Here we make a more explicit link between the tests and their corresponding issues.
> Annotate tests with issue numbers

- exe/Main.hs
- ghcide.cabal
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
This does not yet take advantage of any new features but we should at
least be able to benefit from bugfixes.
> Upgrade to hie-bios 0.3

- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/LSP/LanguageServer.hs
We have some issues in GHCi on the DAML codebase where it complains
about:
<interactive>:28:1: error:
Ambiguous occurrence `hDuplicateTo'
It could refer to either `Development.IDE.GHC.Util.hDuplicateTo',
imported from `Development.IDE.GHC.Util' at compiler/damlc/daml-opts/daml-opts/DA/Daml/Options.hs:36:1-31
or `GHC.IO.Handle.hDuplicateTo', imported from `GHC.IO.Handle'
Given that this is only internal to ghcide anyway, we can just rename it.
> Rename hDuplicateTo to hDuplicateTo'

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
I am trying to implement #231. However, I think I have done something very wrong, because I get a `BadDependency` error message.
@cocreature @ndmitchell could you provide some help? Thanks in advance :)
> Enhancements to top-level signatures

- src/Development/IDE/GHC/CPP.hs
This patch comes from my experience in using ghcide in combination with quasi-quoters which read from files. If you have something like:
```haskell
$(doSomething "from.file")
```
then build tools would take the relative path to start with the source folder of the corresponding project, but ghcide takes it from the root of the project. Until a better solution is found, my proposal is to have this additional define in CPP, so we can do:
```haskell
#if __GHCIDE__
$(doSomething "src/from.file")
#else
$(doSomething "from.file")
#endif
```
> Define "__GHCIDE__" on CPP

- src/Development/IDE/Types/Location.hs
haskell-lsp 0.19 has started to normalise file paths completely so we
need to make sure that NormalizedFilePath agrees with that, otherwise,
we get a bunch of test failures on the daml repo (they are not
specific to DAML, but atm ghcide CI does not run windows).
> Normalise filepaths to match haskell-lsp 0.19

- exe/Main.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Error.hs
- src/Development/IDE/LSP/CodeAction.hs
- src/Development/IDE/Types/Diagnostics.hs
- test/exe/Main.hs
This is another attempt at fixing the problems described by #261. After this patch, warnings which were not enabled explicitly by the user but are needed to support some other functionality (mainly code lenses) are completely filtered out.
The implementation works by keeping two `DiagnosticStore`s in the `IdeState`: the usual one, and a new one of "hidden diagnostics". The means that a call to `getDiagnostics` should do the right thing and show only those warnings which were enabled. You need to call `getHiddenDiagnostics` to obtain the rest of the diagnostics, as done in the code lens code.
> Filter out completely warnings not enabled by user

- test/data/GotoHover.hs
- test/exe/Main.hs
> Test for issue #7

- exe/Main.hs
Shake 0.18.4 started exporting Info from this module which clashes
with the one from haskell-lsp. Fixes #271
> Fix build with Shake 0.18.4

- src/Development/IDE/Spans/AtPoint.hs
- src/Development/IDE/Spans/Documentation.hs
- test/data/GotoHover.hs
- test/exe/Main.hs
This fixes hover for types, classes and type variables.
Information about spans includes a `Maybe Type` which is `Just` for data-level
expressions and `Nothing` for type-level expressions.
`AtPoint.atPoint` which is the oddly-named function responsible for constructing
hover information, runs in the `Maybe` monad, and aborted at the first sight of
a `Nothing`, thus producing no hover information for type-level spans.
In the process of fixing this, I have refactored the function to
+ separate the construction of data-level and type-level hover info
+ make the components that make up the hover info (and their construction) more
clear
I can see plenty little improvements that could be made to the functionality of
the code (and lots that could be made to its organization), but the most …
> Fix #248 and #250

- hie.yaml
Seems to be required or I get errors about Stack not being able to pick flags. I guess this is a hie-bios-0.3 change.
> Make hie.yaml hie-bios-0.3 compatible

- ghcide.cabal
- src/Development/IDE/Core/Preprocessor.hs
- test/exe/Main.hs
- test/preprocessor/Main.hs
Turns out to be rather easy, since GHC exposes very reusable pieces. Works with the example in #279. CC @DoctorRyner
I don't have a great suggestion for how to test this, but I do think a test would be valuable. To do a test we need a preprocessor available with the test suite. We could require record-dot-preprocessor, but that seems a very bad idea. We could write our own small shell script, but that's going to have portability issues. Thoughts?
> #279, support preprocessors

- ghcide.cabal
- src/Development/IDE/LSP/CodeAction.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
- test/exe/Main.hs
To parse and edit module imports I went with a very low tech solution, instead of reusing the GHC parse tree or similar, in the interest of preserving as much of the user text as possible.
To match on the GHC error output I went with *regex-tdfa*, which is able to run regular expressions on `Text` values, because it seems the right tool for the job. While it has an upper bound on `base` that rules out 8.8, it worked for me with `allow-newer`.
> Fix for #45 - remove redundant symbols from imports

- ghcide.cabal
- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Error.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Outline.hs
- src/Development/IDE/Spans/AtPoint.hs
- test/exe/Main.hs
Low hanging fruit, worth doing as VS Code makes document outlines actually useful by adorning them with warnings and errors markers.
> Document symbols provider

- ghcide.cabal
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
Lower versions are pretty horribly broken on Windows. Require a fixed hie-bios to avoid support questions. Closes #281.
> Require hie-bios 0.3.2 or above

- src/Development/IDE/Types/Location.hs
We already normalise filepaths in NormalizedFilePath. haskell-lsp
changed things such that the conversion from Uri to NormalizedUri
normalises the filepath again which caused a significant slowdown in
GetFileExists.
We already have a wrapper for converting from NormalizedFilePath to
NormalizedUri so this PR changes this wrapper to inline the definition
without the additional layer of normalisation.
fixes #298
The corresponding `haskell-lsp` PR that caused the regression was https://github.com/alanz/haskell-lsp/pull/205
Before
After
> Fix performance regression introduced by filepath normalisation

- src/Development/IDE/Types/Location.hs
- test/exe/Main.hs
I accidentally broke this on Windows in #303 by letting the two
conversirons get out of sync.
> Fix check for empty file path

- exe/Main.hs
- ghcide.cabal
Path is useful for diagnosing issues, e.g. a global ghcide being picked up instead of a project one in Nix. 
```
[nix-shell:~/scratch/ghcide]$ ghcide --version
ghcide version: 0.0.5 (GHC: 8.8.1) (PATH: /nix/store/vwdng7227zjsfhzy6c6hcssmbk7yfyki-ghcide-0.0.5/bin/ghcide)
```
Git commit is useful when developing, to make sure tests are running on the expected binary
```
[nix-shell:~/scratch/ghcide]$ cabal run ghcide -- --version
Up to date
ghcide version: 0.0.5 (GHC: 8.8.1) (PATH: /home/pepe/scratch/ghcide/dist-newstyle/build/x86_64-linux/ghc-8.8.1/ghcide-0.0.5/x/ghcide/build/ghcide/ghcide) (GIT hash: 20406624e73263b9f337c3187a5badca88c9cc63)
```
> Extend version message to include path and git commit

- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/GHC/Error.hs
- test/exe/Main.hs
Fixes https://github.com/digital-asset/ghcide/issues/87
> Collect CPP error logs into diagnostics.

- src/Development/IDE/Core/Completions.hs
- test/exe/Main.hs
**Note:** this PR is one half of the one originally in #288
According to #227 (comment), such instances are only required for implementing the "resolve completion" functionality in LSP. However, at this moment all the information is returned directly in the completion request, so there's no need for that. This PR removes the code, and also updates the tests.
> Remove JSON instances for unused completion code

- src/Development/IDE/Spans/AtPoint.hs
- test/exe/Main.hs
Following the first part of the discussion in #101, 
and reusing some code from https://github.com/mpickering/ghcide/commits/wip/type-map.
An interval tree is used to speed up span lookups, which benefits hovers and
definition lookups. The computation of spans is still done using the same
algorithm as previously.
Fixes #247 by sorting matching spans by relevance.
> Speed up span lookups

- src/Development/IDE/LSP/CodeAction.hs
- src/Development/IDE/Types/Location.hs
- test/exe/Main.hs
Initial stab at a code action to insert imports based on GHC suggestions. Outstanding issues  (to my knowledge):
- the suggestions for missing constructors lead to compile errors when applied, see below. To deal with this,  a second code action is provided to fix these imports.
```
In module ‘Data.Maybe’:
‘Just’ is a data constructor of ‘Maybe’
To import it use
import Data.Maybe( Maybe( Just ) )
or
import Data.Maybe( Maybe(..) )
```
- If a missing constructor has the same name as the defining data type (e.g. `Identity`), neither code action can deal with it properly.
I'd say that this PR gets ghcide 80% there. I will add tests for these outstanding issues later today.
> Insert imports code action

- exe/Arguments.hs
- exe/Main.hs
- src/Development/IDE/Core/Shake.hs
The flag provides a way to enable Shake profiling reports without recompiling.
Debug output prints links to the profiling artifacts for convenience.
> Add a new flag --shake-profiling DIR

- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/LSP/CodeAction.hs
- test/exe/Main.hs
The code that I contributed a few days ago was very rudimentary. The new code finds the spans to remove using the GHC parse tree, then manually extends them to include commas/spaces.
Fixes #299
> Smarter logic to remove redundant import bindings

- test/data/GotoHover.hs
- test/exe/Main.hs
Tests for #310.
The most important pair of tests here is the "inner signature" pair. The others
serve mainly to document, compare and contrast what is happening in related
situations.
In summary, hover and gotoDef
+ on inner signatures: give type and location information for the outer
definition; this is misleading,
+ on outer signatures: give no information at all,
+ on inner definitions: give correct information for the inner definition,
+ on outer definitions: give correct information for the outer definition.
Should hover and gotoDef do anything at all for signatures? or is the current
behaviour for outer signatures (doing nothing at all) what we want?
> Tests for issue 310 (misleading hover on inner signature)

- src/Development/IDE/LSP/Completions.hs
- src/Development/IDE/LSP/LanguageServer.hs
- test/exe/Main.hs
This PR makes `ghcide` request a completion every time a dot is pressed. So if you do `Prelude.`, you get the entire list of functions defined in that module.
There's some additional logic to check for the case `id .`, where you want to use `(.)` as the function composition operator. Simply stated, if before the dot we find nothing, and the completion is triggered by that same press of the dot, we give nothing back in return.
> Trigger completion after dot

- src/Development/IDE/Spans/Calculate.hs
- test/data/GotoHover.hs
- test/exe/Main.hs
Currently, we use the source span of the match which corresponds to
the whole clause instead of just the function identifier. This
resulted in us pointing every goto definition request within a clause
to the function if there is no other information (either because it
failed because it came from an external package or simply because you
are not on an identifier).
This PR fixes this by getting the proper source spans frmo the
HsMatchContext. Somewhat annoyingly, we have to get it from the parsed
module since GHC messes this up during typechecking but it’s
reasonably simple.
fixes #315
> Fix source spans for multi-clause definitions

- src/Development/IDE/Core/Completions.hs
- src/Development/IDE/GHC/Error.hs
- src/Development/IDE/LSP/CodeAction.hs
- src/Development/IDE/Types/Location.hs
- test/exe/Main.hs
GHC error messages are quite awesome. If only there was a typed API ...
> Code action to insert new definitions

- .hlint.yaml
- src/Development/IDE/Core/Completions.hs
This fixes an issue that we encountered in DAML. I’ll add a test for
this in the DAML repo since we cannot test the ghc-lib codepath
here (since we don’t setup an environment that works).
> Avoid lookupName on ghc-lib

- ghcide.cabal
GHC does not support multiple `-with-rtsopts` flags: the last one wins
Before this change:
```
[nix-shell:~/scratch/ghcide]$ /home/pepe/scratch/ghcide/dist-newstyle/build/x86_64-linux/ghc-8.8.1/ghcide-0.0.6/x/ghcide/build/ghcide/ghcide  +RTS --info
[("GHC RTS", "YES")
,("GHC version", "8.8.1")
,("RTS way", "rts_thr_p")
,("Build platform", "x86_64-unknown-linux")
,("Build architecture", "x86_64")
,("Build OS", "linux")
,("Build vendor", "unknown")
,("Host platform", "x86_64-unknown-linux")
,("Host architecture", "x86_64")
,("Host OS", "linux")
,("Host vendor", "unknown")
,("Target platform", "x86_64-unknown-linux")
,("Target architecture", "x86_64")
,("Target OS", "linux")
,("Target vendor", "unknown")
,("Word size", "64")
,("Compiler unregisterised", "NO")
,("Tables next to code", "YES") …
```
> Fix -with-rtsopts flags to work as intended

- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/FileExists.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/Notifications.hs
- test/exe/Main.hs
This is a minimal solution that does not entirely follow the plan in #101, focusing on GetFileExists instead of GetLocatedImports. 
In my experiments it solves the problem, hopefully without breaking anything else. Checked with VSCode only. 
Adding tests is tricky since lsp-test does not send DidChangeWatchedFiles notifications. I'm open to suggestions on what to do.
Leveraging DidChangeWatchedFiles notifications for other purposes, e.g. in the GetModificationTime rule, is left for future PRs.
> Fix performance of getFileExists

- src/Development/IDE/GHC/CPP.hs
This PR fixes the build for ghc 8.8.2 by using the new `LlvmVersion` API (which no longer exports constructors).
Fixes #334.
> Fix the build for ghc-8.8.2.

- src/Development/IDE/Core/FileStore.hs
This was causing the following error when trying to build under MinGW:
[28 of 38] Compiling Development.IDE.Core.FileStore
C:\Snapshot\src\ghcide\src\Development\IDE\Core\FileStore.hs:142:20: error:
Not in scope: `Dir.getModificationTime'
No module named `Dir' is imported.
|
142 |         do time <- Dir.getModificationTime f
|                    ^^^^^^^^^^^^^^^^^^^^^^^
---
I came across this while working on #336, which I happened to troubleshoot under a Windows machine.
> Fix build on Windows/MinGW

- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Spans/AtPoint.hs
- src/Development/IDE/Spans/Calculate.hs
- src/Development/IDE/Spans/Type.hs
- test/exe/Main.hs
Fixes #283.
The implementation works by collecting constraints from `AbsBinds`, and then filtering those which are in the range of the variable to show and which have some free variable in common with the type to be shown. The new `SpansInfo` type collect info for both expressions and types.
> Show constraints on hover

- src/Development/IDE/Spans/Documentation.hs
This has caused a bunch of issues in DAML where GHC seems to randomly
panics when completions are requested, see
https://github.com/digital-asset/daml/issues/4152 for the error. I am
not entirely sure what is going wrong there but `getDocs` also goes
through the GHCi codepaths which are known to cause issues with
ghc-lib so for now, let’s disable it.
> Disable getDocs call with ghc-lib

- .hlint.yaml
- src/Development/IDE/Spans/AtPoint.hs
Fixes #346.
I never managed to reproduce the bug, but the nameModule function seems destined to cause random issues - it works on 99% of identifiers, so goes wrong in a few corner cases. Using the `_maybe` variant is simple and safer.
> #346, don't use nameModule, which raises errors

- .hlint.yaml
- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Plugin/Completions/Types.hs
Move the things into Plugin, expose them, and then put them back after. Aim is to migrate them to haskell/ide/plugin as two separate plugins.
Note this will require the DAML compiler to use these plugins.
> Move the completions and code actions into Plugin

- src/Development/IDE/Core/Rules.hs
I also confirmed it wasn't used in DAML.
> Delete unused function

- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
Some GHC extensions were not supported in the code actions, for instance `NamedFieldPuns` didn't work because within GHC the internal extension name is still `RecordPuns`. This patch fixes this issue.
> Improve recognition of GHC extension names

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Util.hs
There's no need for them to be a separate rule. Also makes them more efficient by avoiding reading the file twice, and makes them more correct by taking the fingerprint after `#include` files etc.
> Simplify fingerprint computations

- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/GHC/CPP.hs
- test/exe/Main.hs
Before it was in upstream code we wanted to reshare. Now it's not. Makes the GHC 8.10 upgrade better. I also added a test.
> Move the definition of __GHCIDE__

- ghcide.cabal
- src/Development/IDE/Spans/Common.hs
- test/exe/Main.hs
> Enhancements to Haddock -> Markdown conversion

- src/Development/IDE/Core/Debouncer.hs
- src/Development/IDE/Types/Location.hs
Two changes in this patch make performance quite a lot better for all actions.
1. Cache the conversion to `NormalizedUri` from `NormalizedFilePath`
2. Use a hash map for the debouncer to take advantage of the fast hash instance of `NormalizedUri`. 
The cached `Hashable` instance is in this PR: https://github.com/alanz/haskell-lsp/pull/214
My benchmark which ran hover 1000 times went down from 259s to 37s including initialisation time. Hovering on large projects is not noticeably faster (1s vs < 0.1s). 
Reviewer: @pepeiborra 
Note: I removed the Eq/Ord instance from Pepe's original patch because they relied on the hash for comparing equality. There are some hotspots on the latest profile from
> Improve performance by caching conversion to NormalizedUri

- ghcide.cabal
- test/exe/Main.hs
Given that the code for this lives in ghcide it makes no sense for the
tests to be part of the DAML repository.
> Migrate tests for position mapping from DAML repository

- ghcide.cabal
- src/Development/IDE/Spans/Common.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- test/exe/Main.hs
I don't see any reason for supporting old versions of haddock-library. Might as well just demand the latest everywhere (and see if the CI disagrees with me).
> Don't support old haddock-library versions

- test/exe/Main.hs
These doc tests fail on GHC 8.6.4, so restrict them to 8.6.5 and above. See https://github.com/haskell/haskell-language-server/issues/22
> Require GHC 8.6.5 for some docs tests

- src/Development/IDE/LSP/HoverDefinition.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Outline.hs
- src/Development/IDE/LSP/Server.hs
- src/Development/IDE/Plugin.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Completions.hs
An LSP response message can have either a result or an error
field. Expose this in the handler by having a return type
type ResponseBody resp = Either ResponseError resp
Closes #395
> Allow the withResponse handler to idiomatically return an error

- ghcide.cabal
- src/Development/IDE/Core/Shake.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
Instead of saying how many nodes are in the Shake graph, we instead say how many files have started in the Shake graph. Unlike the previous measure, it isn't guaranteed to be monotonically increasing, as you might start additional rules after running files. But, in practice it seems pretty good, as we're hooking in somewhere very low level, the numbers "have the right feel" - when I have a project open the number roughly corresponds to the number of files, and roughly feels like the work is checking files. It also has more overhead, but if that's a problem, could be redone in terms of IORef to avoid the Var.
Probably worth someone other than me also playing with it to confirm it "feels right".
Fixes #320
> Better progress messages

- exe/Main.hs
Ghcide via LSP uses absolute paths, but via the command line tester uses relative paths. As a consequence the nasty thing I was debugging worked perfectly, so better to make everything work the same if we possibly can.
> Make ghcide on the command line use absolute file paths

- src/Development/IDE/Core/Shake.hs
At the moment it flickers a progress bar a lot, which is annoying. I first tried 0.3s but that made it almost never show, which felt wrong. 0.1 seems to have reasonable ergonomics.
> Only show progress messages if the computation takes > 0.1s

- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/Rules.hs
The VFS already provides it as Text, and getFileContents converts it
to a StringBuffer.
Expose the intermediate step so that tools such as formatters can
access it without a double conversion.
> Allow getting file contents as Text 

- exe/Main.hs
- ghcide.cabal
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
Updates ghcide to use the latest hie-bios version 0.4.0
> Update to latest hie-bios

- src/Development/IDE/GHC/CPP.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
Now the progress thread gets killed more robustly, so progress messages always stop.
> #381, require shake-0.18.5, which ensures progress cancellation is robust

- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/Debouncer.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
We have been experiencing a few flaky tests in DAML caused by our CLI
compiler losing diagnostics. The reason for that is the debouncer
which meant that messages got delayed and not send before the process
exited.
This PR makes the debouncer abstract and adds a noopDebouncer which
doesn’t do any debouncing. This is also what we use in the terminal
ghcide test thingy.
> Make debouncer configurable

- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/FileExists.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Import/DependencyInformation.hs
- src/Development/IDE/LSP/Notifications.hs
- stack84.yaml
Now that we have optimized Hashable instances for these, it makes
sense to use this consistently.
> Use HashMap/HashSet for maps indexed by Normalized{FilePath,Uri}

- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/Shake.hs
This is needed to be able to compare them, which we need for loading `.hie` and `.hi` files.
Another spinout from the effort to switch to interface files (#355)
> Change the representation of filestamps

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Spans/Calculate.hs
- src/Development/IDE/Spans/Documentation.hs
Just a simple refactoring to scope down the inputs in `getDocumentation` to what is actually being used. This is a spinout from the effort to switch to interface files (#355)
> Change getDocumentation to work with parsed modules

- src/Development/IDE/Core/Compile.hs
- test/exe/Main.hs
Running the simplifier is necessary to do things like inline data
constructor wrappers.
Fixes #256 and #393
> Run simplifier before generating ByteCode

- ghcide.cabal
- src/Development/IDE/Core/FileExists.hs
- src/Development/IDE/Core/IdeConfiguration.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Notifications.hs
- src/Development/IDE/LSP/Outline.hs
- src/Development/IDE/LSP/Server.hs
- src/Development/IDE/Plugin.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Completions.hs
- test/exe/Main.hs
This is a correctness fix for `getFileExists` when targetting files out of the workspace - they cannot be watched by the client so we need to fall back to the slow path.
This is a spinout from the effort to switch to interface files (#355).
> Workspace roots and getFileExists

- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Import/DependencyInformation.hs
- src/Development/IDE/Import/FindImports.hs
- src/Development/IDE/Plugin/Completions.hs
Another spinout from the effort to switch to interface files (#355), joint work with @lazamar 
This is needed to reason about dependencies at the module level, in particular to tell whether a dependency is a home module or a package module
> Track module dependencies

- exe/Main.hs
- ghcide.cabal
- hie.yaml
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
hie-bios's componentDependencies returns the dependencies of a cradle
that might change the cradle. Add those deps to the shake graph so that
the GHC session is newly created whenever they change.
For that, add a new rule type, GetHscEnvEq, to cache GHC sessions with
the key of GHC options and dependencies. And delete the optGhcSession
field from IdeOptions.
This is for https://github.com/digital-asset/ghcide/issues/50.
hie-bios's componentDependencies can return files that don't exist yet:
https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Types.hs#L90-L93.
This PR handles changes in the existing dependency files, but doesn't
handle newly created dependency files.
> Automatically pick up new dependencies

- ghcide.cabal
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/CodeAction/PositionIndexed.hs
- test/exe/Main.hs
- Redundant "All" imports, e.g. Maybe(..)
- Redundant datatype plus constructors, e.g. Maybe(Just)
Fixes #352
> Fix corner cases in remove redundant imports code action

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
The implementation looks in modules loaded from the package database. It should
only look in packages declared as dependencies of the project. The package
modules are loaded lazily and are global to the HscEnv, so the success rate will
depend on what has been loaded so far in the env.
I intended to make this as a standalone plugin but we cannot have two plugins providing code actions, see https://github.com/haskell/haskell-language-server/issues/25#issuecomment-586704493
> Code action to suggest adding missing imports from pkg db

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Import/DependencyInformation.hs
- src/Development/IDE/Import/FindImports.hs
Previously `PathIdMap` cached `NormalizedFilePath` values, but with the addition of module data those got dropped.
It's probably a good idea to bring them back to avoid the risk of a perf regression
> Cache NormalizedFilePath in ArtifactLocation

- src/Development/IDE/LSP/Outline.hs
- test/exe/Main.hs
Makes it easier to see symbols in scope when you have lots of
import statements.
Bikeshedding:
Should a single imports still be wrapped into a DocumentSymbol?
In manual tests, behaviour is as I would have expected it.
@ocharles Can you test if your work-flow still works?
closes #438
> Group Imports in Outline into a single node

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Spans/AtPoint.hs
`.hie` files are used instead of typecheck artifacts for `getDefinition` functionality when using interface files, as they lack located typechecked ASTs.
We choose to never store .hie files in the Shake graph, as they are
- expensive in space
- quick to load
- only used for go to definition
While there, we remove package module .hie files from the Shake graph too.
> Add .hie files support for home modules

- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/GHC/CPP.hs
Unfortunately PR #377, which was meant to help with GHC 8.10 compatibility, also requires a fix for GHC 8.10.
Recent versions of GHC's `DynFlags` module define an [`addOptP` function](https://gitlab.haskell.org/ghc/ghc/blob/ghc-8.10/compiler/main/DynFlags.hs#L2716), but it is unfortunately not exported, so the definition is copied here.
With this additional fix, the master branch of `ghcide` builds on GHC 8.10 rc1 on my end.
> Adjust PR #377 for GHC 8.10 (DynFlags/Settings optP)

- exe/Main.hs
- exe/RuleTypes.hs
- ghcide.cabal
We were calling `runCradle` multiple times per cradle, concurrently. For Cabal
cradles this function runs Cabal, which is neither fast nor designed to be run
concurrently
Fixes #446
> Fix regression in cradle loading logic

- exe/Main.hs
Without this I kept getting:
```
commitAndReleaseBuffer: invalid argument (invalid character)
```
And then ghcide the command line tester fell over. With this, I get garbage quote characters, which actually lets me see the words at least.
> Set the streams to utf8 in Main.hs

- exe/Main.hs
- exe/Rules.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Types/Options.hs
isTesting got added to ShakeExtras unnecessarily
> Refactoring: remove isTesting from ShakeExtras

- .gitignore
- README.md
- ghcide.cabal
- stack.yaml
- stack84.yaml
- test/exe/Main.hs
Use by
stack --stack-yaml=stack84.yaml test --test-arguments "--rerun"
> Use tasty-rerun to allow rerunning failed tests only

- ghcide.cabal
- src/Development/IDE/LSP/HoverDefinition.hs
For use in haskell-language-server
The way `PartialHandler`s are chained in ghcide means earlier ones get masked by ones added later in the chain.
haskell-language-server puts a hover handler in to the custom area, which combines the output of all configured hover handlers.
This change allows hls to include the underlying one for ghcide.
We treat gotoDefinition the same way, if we choose to combine them at the plugin level.
> Expose underlying hover and gotoDefinition handlers

- src/Development/IDE/Core/Compile.hs
- test/exe/Main.hs
Seems like this was never implemented the first time, woops!
Fixes #424
> Pass correct SafeHaskell information to mkIfaceTc

- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Types/Options.hs
This is necessary for DAML where we have additional
keywords (e.g. `with`) and other keywords don’t
exist (e.g. `foreign`).
I considered using just a modify function `[T.Text] -> [T.Text]`
but decided against it in the end. The list is small enough and I
think it’s much easier to understand with an explicit enumeration (and
you can just show the field in the options which is often convenient
for debugging).
> Make keywords customizable

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
It causes problems for our conversion to DAML-LF atm and isn’t
necessary (since we don’t have template Haskell) so let’s make it
configurable. I originally thought we could just copy paste all of
compileModule to DAML but it turns out that this pull in too much
stuff that I don’t want to see diverge from `ghcide` so I abandoned
that idea.
> Allow disabling the simplifier in compileModule

- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- test/exe/Main.hs
The completion context determines whether we show completions for
types or completions for values. This is done by looking at the parsed
module.
This PR fixes two things:
1. While we only use the parsed module for getting the context
previously we got the parsed module out of the typechecked
module. This means that if you have a module that parses but
doesn’t typecheck, we will use the parsed module at the point where
it last typechecked which is out of date and produces incorrect (or
just no) contexts.
2. When we could not find a context, we defaulted to assuming we are
in a value context. Especially in combination with 1 but also just
in general, this is rather annoying. If we aren’t sure we should
show the user everything we have and not filter out some
completions. Filtering out …
> Improve completion contexts

- exe/Rules.hs
- exe/Util.hs
- ghcide.cabal
- src/Development/IDE/GHC/Util.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
Note that this PR builds on top of #460 
This PR makes ghcide fail early if the compile-time and run-time versions of ghc do not match, with a clear error message that should decrease the maintenance burden. It builds on top of a tiny package called `ghc-check` that I have put together to encapsulate the potentially reusable bits.
The PR may require adjustment for ghc-lib, but I'm not entirely sure under which scenarios ghc-lib is used, and what it means to use ghc-lib instead of ghc.
> Detect ghc mismatch

- .hlint.yaml
- ghcide.cabal
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Error.hs
- src/Development/IDE/GHC/Orphans.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/GHC/WithDynFlags.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Spans/Calculate.hs
- test/exe/Main.hs
Instead of full modules, ghcide now parses only the module headers and avoids storing unnecessary ASTs in the Shake graph where possible. This happens in a couple of places:
* Locating the imports of a module. Now this uses a `ModSummary` instead of a `ParsedModule`
* For computing all the completions in a module. Now this uses a `ModIface` instead, i.e. a `.hi` file. 
* For computing source span infos, the parsed modules are only used when building against `ghc-lib`.  Otherwise, `ModIface` is used instead. 
* Interface files created by ghcide now embed Haddocks
Altogether, ghcide only parses full modules for files of interest now, or for dependencies when an up-to-date `.hi` file is not available. The main benefits are 
1. shorter start-up times 
2. lower memory usage. 
Joint work with …
> Parse module headers

- .hlint.yaml
- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Compat.hs
- src/Development/IDE/Plugin.hs
- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
A client can run more than one instance of ghcide.  Some clients have a global
command registry, and all commands must be unique in that registry.
So to make the command ids unique, prefix them with the ghcide server process
id, as is done in haskell-ide-engine.
> Add a custom prefix to command IDs

- README.md
The README mentions a blog post by Marco Lopes from 2019 but I hit bugs or configuration issues at every step. For example Marco's guide says "set up coc.nvim" but doesn't provide the full ``coc-settings.json`` file, nor does it say where to put it. And the sample doesn't work with the current ``hie-wrapper`` (I got duplicate "starting..." messages and nothing happened).
In the interest of reproducibility I created a Dockerfile that builds ghcide, haskell-ide-engine, Neovim, and coc.nvim, configures each component, and sets up a hello-world project to confirm that everything works.
> Update README with link to Docker build for Neovim and ghcide

- exe/Rules.hs
- ghcide.cabal
- src/Development/IDE/GHC/Util.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack84.yaml
- stack88.yaml
- retrieve runtime version from ghc executable, not from pkg db (ghc-check 0.3.0.0)
- Do not fail if unable to retrieve runtime version
Fixes #534 and #536
> Improve ghc version check

- ghcide.cabal
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
lsp-test-0.11 has replaced openDoc' with createDoc which sends out workspace/didChangedWatchedFiles notifications, so the wrapper in https://github.com/digital-asset/ghcide/pull/322 shouldn't be needed anymore
> Upgrade to lsp-test-0.11

- exe/Rules.hs
Sometimes one needs to clear up the cache dir manually, e.g. if GHC is unable to detect that the interface files are stale and need rebuilding. This change is aimed at making the discovery of the cache dir location a bit easier. There are two changes
1. Log the cache dir location at startup,
2. Make the cache dir local to the project, as not every lsp client makes it easy to retrieve the lsp server logs
> Log cache dir

- src/Development/IDE/Core/Rules.hs
- test/exe/Main.hs
Do I also need to `need` the files or is calling `doesFileExist` enough to track the dependency?
> Track dependencies when using qAddDependentFile

- src/Development/IDE/Core/PositionMapping.hs
- src/Development/IDE/Core/Shake.hs
Please review this commit by commit. 
The first three commits are just about fixing space leaks.
The fourth commit is a comment warning about not unfixing the leak.
The fifth commit is a refactoring which makes the correctness of the first commit more obvious but seemed distracting to include in the same commit.
> Fix 3 space leaks and refactoring of PositionMapping

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Import/FindImports.hs
There are two reasons why this patch is good:
1. We remove the special case of the initial module from the dependency
search. It is now treated uniformly like the rest of the modules.
2. rawDependencyInformation can now take a list of files and create
dependency information for all of them. This isn't currently used but on
my fork we have a rule which gets the dependency information for the
whole project in order to create a module graph.
It seemed simplest to upstream this part first, which is already a
strict improvement to make the overal patch easier to review.
> Refactor rawDependencyInformation

- src/Development/IDE/Core/Shake.hs
Follow up from #557. We definitely want the progress state to be fully evaluated, so demand that with evaluating functions like evaluate and $!, rather than relying on the compiler to get it right. My guess is the `$!` is unnecessary now we have `evaluate`, but it's also not harmful, so belt and braces approach.
> Remove space leaks in a more robust way

- src/Development/IDE/Core/Shake.hs
In 0.18.4 deprioritize was renamed reschedule, so follow the new name.
> Avoid deprecated Shake functions

- src/Development/IDE/Core/Shake.hs
When debugging for space leaks this stood out as weird - an ADT where some alternatives are strict in their fields, and some aren't. I don't think it has any impact, but seems the right way to go.
> Make VFSVersion strict

- src/Development/IDE/Core/Shake.hs
Before we hashed all unary constructors (e.g. DoesFileExists, GetModificationTime) to the same constant (via the Generic Hashable instance), and thus treated these keys as all equivalent, and thus got tons of hash collisions, and thus got space leaks via https://github.com/tibbe/unordered-containers/issues/254. Much better to _not_ have hash collisions or space leaks, which we do by hashing in the type, like Shake does.
While writing this patch my first approach was to copy Shake, which does `hashWithSalt salt type 'xor' hashWithSalt salt value`. That is terrible because `(,)` uses `hashWithSalt` to merge the pair together, and if you xor two salts that have been xor'd you end up cancelling them out, and go back to collisions galore. I'm going to go fix Shake (I don't think it matters …
> Fix the Hashable instance of Key

- .gitignore
- .hlint.yaml
- bench/Main.hs
- ghcide.cabal
- hie.yaml
The benchmark suite is designed to be run with `cabal bench`. It does not attempt to compare with past performance, I think that's better tackled as a separate task.
The module comment in the benchmark module contains some details on the benchmark methodology and experiments, which currently cover the basics:
- hover
- go to definition
- completions
- code actions
- document symbols
I have not made any attempts to integrate with CI since I don't know how consistent the timings would be across runs. 
Goes some way towards closing #242
> Benchmark suite

- src/Development/IDE/Core/Rules.hs
It is subsumed by the GetModificationTime dependency.
One less dependency per .hi file,
one less redundant file system access,
five fewer lines of code.
This does *not* implement all the improvements discussed in #583, it's just a minor efficiency fix.
I have not measured the performance impact either, since there is no easy-to-run standard benchmark, but I expect the impact to be very small.
> remove unnecessary FileExists dependency in GetHiFile

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/LSP/HoverDefinition.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/Spans/AtPoint.hs
- test/data/hover/hie.yaml
- test/exe/Main.hs
The test fails for some reason locally but works in the editor so if someone knows how to fix it then please tell me.
> Implement Goto Type Definition

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Error.hs
- test/exe/Main.hs
Fixes #573. Downgrade Haddock errors to warnings, and prepend Haddock in front of them. Now we are manipulating Haddock warnings, its easier to dedupe them by range than trying to merge arbitrary diagnostics.
> #573, make haddock errors warnings with the word Haddock in front

- .ghci
Allegedly it's possible to develop Ghcide without using Ghcid. I am yet to be convinced, and certainly I can't do it.
> Add back a .ghci file

- src/Development/IDE/Types/Location.hs
When there is a catastrophic failure to load a cradle (e.g. #610) the consequence is that every file is highlighted in red everywhere. If you want to continue developing with something like Ghcid it's super annoying to have to try and see the code under this sea of red. Solution is to treat cradle errors as being diagnostics spanning the first line of every file. It's still clear the error is there, you can still look at it, but it's not all you have to look at. There's no good reason to highlight an entire file in red.
> Use a better noRange

- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Types/Diagnostics.hs
> Restore Shake profiling

- src/Development/IDE/Core/Rules.hs
GetSpanInfo allowed stale dependencies prior to #457 and was changed to disallow them for no good reason, which makes hovers unavailable when a dependency doesn't typecheck
While I was there, I also dropped early cutoff from GetHiFile as it seems unnecessary. 
No impact in performance:
```
name                       | samples | startup | setup | experiment | maxResidency
-------------------------- | ------- | ------- | ----- | ---------- | ------------
hover                      | 10      | 7.50s   | 0.00s | 9.71s      | 168MB       
hover after edit           | 10      | 7.25s   | 0.00s | 13.61s     | 151MB       
getDefinition              | 10      | 7.24s   | 0.00s | 5.92s      | 145MB       
documentSymbols            | 100     | 7.25s   | 0.00s | 1.43s      | 28MB …
```
> Allow stale data back in GetSpanInfo rule

- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
After merging #589 ghcide now errors out occassionally with `internal error - GetHiFile of file of interest`. 
This is great! It uncovers a real bug in `getHiFileRule`, although I'm not sure if the bug would have any user impact.
The problem is that `getHiFileRule` has direct dependencies on `GetHiFile`, which is wrong for the reasons explained in the expanded comment.
> Fix a bug in getHiFileRule

- hie.yaml.cbl
- hie.yaml.stack
* I think ghcide is already supporting the none cradle so we will leverage it here
* The stack based hie.yaml could be handy for stack users (not sure if it should be the default one)
> Add hie.yaml.stack and use none cradle for test data

- test/exe/Main.hs
On macOS, the $TMPDIR folder leads to /var/blahblahblah, but this is canonicalized to /private/var/blahblahblah for reasons beyond my understanding. Either way, there were some test failures because of a mismatch between the two, so canonicalize the Uris inside the locations to fix this.
The error looked like:
```
simple-multi-test:                                         FAIL (13.67s)
test/exe/Main.hs:1312:
expected: Location {_uri = Uri {getUri = "file:///var/folders/zh/fqwj2cq95b7gbzs49fsq5drw0000gn/T/extra-dir-50174116387/a/A.hs"}, _range = Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 3}}}
but got: Location {_uri = Uri {getUri = "file:///private/var/folders/zh/fqwj2cq95b7gbzs49fsq5drw0000gn/T/extra-dir-50174116387/a/A.hs"}, _range = …
```
> Canonicalize the locations in the cradle tests

- bench/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/Shake.hs
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
This extends the benchmark suite with 
- two new experiments
- fixes for some of the issues reported in #617 
- Basic memory usage stats (unreliable due to https://github.com/bubba/lsp-test/issues/70)
- much better ouptut
- additional config flags, which I'm using to automate perf analysis elsewhere
> More benchmarks

- .gitignore
- bench/Hist/Main.hs
- bench/README.md
- bench/hist.yaml
- ghcide.cabal
- hie.yaml
- hie.yaml.cbl
- hie.yaml.stack
- stack84.yaml
This adds a new script `benchHist` to automate the running of `ghcide-bench` over multiple versions of the project, and produces `.csv` files and `.svg` graphs with the results. More details in the module header and the README.
By default running `stack exec benchHist` will produce an analysis comparing HEAD with upstream, assuming everything works. The analysis is configurable via a yaml file.
I have uploaded a sample output here: https://github.com/pepeiborra/ghcide/tree/bench-hist-dump/bench-hist 
Some interesting results from the analysis:
- Neil's Hashable PR really hit the leak right in the thunk:
- Interface files did curb memory usage! 
- But they also made some things twice as slow (and I have a PR coming):
> Performance analysis over time

- bench/Main.hs
- exe/Main.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Util.hs
Extracted from #624 as this has started biting me too after upgrading cabal-install in my development environment
> Write a cabal.project file in the benchmark example

- src/Development/IDE/Core/Shake.hs
This fixes a race condition in the ShakeSession logic for reenqueuing user actions.
> Fix crash when writing to a Barrier more than once

- exe/Main.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/LanguageServer.hs
To do this we pass in the withProgress and withIndefiniteProgress functions from LspFuncs into ShakeExtras
Supersedes #627
> Report progress when setting up cradle

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
This code action uses an unreliable heuristic, i.e. substring matching
for all existing language extensions.
The "quickfix" LSP action chooses an arbitrary code action from the
list, presumably the first in the list.
As an example, the redundant import
`import Data.Map.Strict`
will trigger the suggestion to add the language extension "Strict".
Moving this suggestion to the end of the list reduces the likelihood
for false positives.
----
Since selection of the quickfix action happens outside of ghcide, there's probably a better solution.
Any suggestions? A better workaround could be to check for the language extension's name's presence in the offending code.
I added a test but it fails and I don't see the definitions of `getCodeActions` and `executeCodeAction`. Some advice would be …
>  Remove `Strict` from the language extensions used for code actions

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Spans/Calculate.hs
I recently discovered that the `.hi` files PR had regressed the performance of `GetSpanInfo` quite noticeably. This is due mostly to a change in the extraction of `spanInfoDoc`s. Prior to the interfaces change, these were mined out of parsed ASTs. `.hi` files don't come with ASTs but instead bundle the haddocks for identifiers. But to be able to use them, we need to:
1. set up a GHC session with all the transitive `.hi` files 
2. rely on [getDocs](https://hackage.haskell.org/package/ghc-8.10.1/docs/GHC.html#v:getDocs) to extract them
Step 1 can be sped up easily by caching a GHC session per module for files of interest, which makes `GetSpanInfo` as speedy as it used to be, as seen in the "hover after edit" experiment.  I was hoping it would also speed up typechecking, but the edit …
> Cache a ghc session per file of interest

- exe/Main.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
Now `GhcSession` tracks the component dependencies, and `GhcSessionIO` (no file) tracks the set of components. Since `GhcSession` has a dependency on `GhcSessionIO`, this works out as intended: if the set of components changes, all the Ghc sessions become invalidated. Otherwise, a Ghc session is invalidated only when the component dependencies (e.g. the Cabal file) change.
Another 10% perf improvement.
Fixes #619 
Benchmarks where HEAD is this patch, upstream is the previous master:
```
version    name                         success   samples   startup              setup                experiment           maxResidency
upstream   hover                        True      100       10.008805828         0.0                  1.0496357980000002   138MB
upstream   edit …
```
> Finer dependencies for GhcSessionFun

- .azure/windows-stack.yml
It keeps crashing and annoying everyone. The issue is in GHC not in
our code and I believe it’s fixed in HEAD already but that doesn’t
help us so let’s add some retries for now.
> Retry GHC 8.10 on Windows

- src/Development/IDE/Core/Debouncer.hs
The indirection caused by `async (sleep 0 >> fire)` was causing non-deterministic ordering of progress done messages and diagnostics, which makes the code actions benchmark experiment fail randomly.
> Fix debouncer for 0 delay

- stack810.yaml
> stack810.yaml: bump

- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
This is my first contribution. My goal is contribute to haskell-language-server / ghcide constantly. This adds a code action that deletes unused top level binding.
Please, let me know how this should be improved.
This closes #54 (I think)
> Delete unused top level binding code action

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
This PR adds code actions to generate suggestions for missing constraints, both for `instance`s declaration and type signatures. I've handled cases where no, one or more other constraints are already declared.
I've also introduced operators like `>>>`, `&`, `<&>` in order to compose from left to right (like the code flows from left to right) and to have code more easier to read and to reason about. I'm mentioning this because I didn't see them used in the code (at least not in the files I changed), so if for some reason they are not welcome, I'll change them.
This closes https://github.com/digital-asset/ghcide/issues/345.
> Code action: add constraint

- bench/lib/Experiments.hs
- cabal.project
- exe/Arguments.hs
- exe/Main.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/HoverDefinition.hs
- src/Development/IDE/LSP/Notifications.hs
- src/Development/IDE/LSP/Outline.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Spans/AtPoint.hs
With this patch whenever any request made by the user is dealt with by an `IdeAction` which has the implicit guarantee to never block for an unbounded amount of time. 
Stale information is used if it's available to answer all requests. Information should usually be up-to-date because the `FileStore.hs` rule requests up-to-date information whenver a file changes. 
Do not review the changes to the hover/completions etc code too closely because that is all rewritten on another branch by Zubin anyway to use HieDb. 
This patch also lays the way for removing `kick` and more fine grained control over which files are typechecked.
> Use stale information if it's available to answer requests quickly

- fmt.sh
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Orphans.hs
- test/data/TH/THA.hs
- test/data/TH/THB.hs
- test/data/TH/THC.hs
- test/data/TH/hie.yaml
- test/exe/Main.hs
This PR follows the plan outlined in #660 including tests. 
Our current benchmark example (Cabal)  doesn't include any example of TH, so the only thing visible in the benchmark results is that things do not regress too much: 
| version  |  name                       |  success |  samples |  startup            |  setup              |  experiment          |  maxResidency |
| -------- | --------------------------- | -------- | -------- | ------------------- | ------------------- | -------------------- | ------------- |
| upstream |  code actions               |  True    |  100     |  10.000944527000001 |  0.59697904         |  0.68091352          |  196MB        |
| HEAD     |  code actions               |  True    |  100     |  9.981281715000001  |  0.9265053580000001 |  0.905302617 …
> Avoid excessive retypechecking of TH codebases

- src/Development/IDE/Core/Rules.hs
- test/data/hover/Bar.hs
- test/data/hover/Foo.hs
- test/exe/Main.hs
The regression was introduced in #630.
I added `GhcSessionDeps` with the idea of reusing the typecheck GHC session
for computing the SpanInfo, instead of rebuilding it from scratch.
But I forgot to actually reuse it, or maybe the change got lost during the merge.
> Fix spaninfo Haddocks for local modules

- .hlint.yaml
- bench/hist/Main.hs
- bench/lib/Experiments.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Plugin/Completions/Types.hs
- src/Development/IDE/Spans/Common.hs
- src/Development/IDE/Spans/Documentation.hs
- test/exe/Main.hs
A completion request immediately after an edit is slow because currently `ProduceCompletions` depends on `Typecheck`, for very little reason. 
Following the plan in #655, we split `ProduceCompletions` in two rules, for local and non local (imported) completions.
- The non local completions reuse all the existing code paths, but depend only on `ModSummary`, which has early cutoff and thus do not recompute during module body edits.
- The local completions are extracted from the parsed module, reusing type signatures where available for type information. 
The speed up is visible in the completions after edit benchmark:
The rest of benchmarks stay the same:
```
pepe:~/scratch/ghcide$ column -ts,  bench-hist/results.csv 
version    name                         success   samples   startup …
```
> Completions need not depend on typecheck of the current file

- exe/Main.hs
- ghcide.cabal
- src-ghc810/Development/IDE/GHC/HieBin.hs
- src-ghc88/Development/IDE/GHC/HieBin.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Compat.hs
- test/exe/Main.hs
This backports [this GHC MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3199) in preparation for a larger role for `.hie` files in ghcide.
We now have a global shared `NameCache` referenced by `ShakeExtras`, which we use to read `.hie` files.
> Use a global namecache to read `.hie` files

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
This PR adds a code action to add default type annotation suggested by GHC when `-Wtype-defaults` is enabled. 
I noticed that during development, when I use `traceShow` from `Debug.Trace` I often get annoyed by sudden warning displayed, so I usually urged to add that default type annotation manually. These changes add a way to do that via a hotkey.
I hope this is useful to someone else.
These changes handle only literals, not expressions. For example for binding `f = 2 + 2` (without type signature defined) the warning will be shown, but no code action produced.
I've tried to handle all the cases of the appearance of this warning, and I am interested in finding more examples to handle (if there is some).
If this doesn't seem like a useful addition, I am fine with not merging it
> Code action add default type annotation to remove `-Wtype-defaults` warning

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Spans/Calculate.hs
- src/Development/IDE/Spans/Common.hs
- src/Development/IDE/Spans/Documentation.hs
Avoiding duplicate work and batching ghc-api lookups for both `getDocs` and `lookupName` are the main sources of improvement. 
As a bonus I also removed usage of the GHCi code paths. Since there is no way for me to test if this fixes the ghc-lib issues, I'm happy to put the CPP pragmas back if that's preferred.
Full benchmarks in: https://github.com/pepeiborra/ghcide/tree/perf-spaninfo-benchmark
> Performance improvements for GetSpanInfo

- exe/Main.hs
- ghcide.cabal
- stack-ghc-lib.yaml
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
New features:
* Store dependencies in CradleError
* Add shell and dependency-shell attributes to bios cradle type
* Add getRuntimeGhcLibDir and getRuntimeGhcVersion functions through a new runGhcCmd API
Relevant bug - fixes:
* Detect implicit cabal cradle in the absence of cabal.project
* Dont resolve symlinks in cradle discovery
* Make Cradle dependencies for stack and cabal more reasonable
* This ships with a known bug: stack lists cradle dependencies from sub-directories incorrectly
* Improve filtering of rts arguments from stack and cabal cradles
* Add cabal.project.local to cabal cradle dependencies
> Update hie-bios to 0.6.1

- stack-ghc-lib.yaml
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
- test/exe/Main.hs
Currently these tests assume stack and will fail when launched with `cabal test`. 
This change acknowledges that failure as expected
> Expect bench experiments to fail with Cabal

- exe/Main.hs
- exe/Utils.hs
- ghcide.cabal
- stack-ghc-lib.yaml
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
- test/exe/Main.hs
#693 needs to be merged first
This replaces hardcoding the GHC libdir path with ghc-paths and instead
gets it at runtime through the hie-bios cradle. This means that the
ghcide binary should be a bit more distributable now, since it won't
rely on paths baked at compile time that are local to the machine it was
compiled on
> Obtain the GHC libdir at runtime

- cabal.project
Fixes the `cabal.project` build in 8.10.1
> Relax upper bounds for GHC 8.10.1

- .gitignore
- src/Development/IDE/Core/Compile.hs
While converting [LiquidHaskell into a plugin](https://github.com/ucsd-progsys/liquidhaskell/pull/1683), we tried to integrate it with `ghcide`. It has been a journey with some lumps and bumps, but eventually we succeeded (with proviso). The plugin itself requires the minimum version of GHC to be `8.10.1` (for technical reasons) and soon enough we discovered that plugins and `8.10.1` don't get along too well, mostly due to https://gitlab.haskell.org/ghc/ghc/-/issues/18070 (which was originally discovered as part of  #556).
However, I've tried building a custom `ghc` version (via Hadrian, as Leon Schoorl mentioned in that GHC ticket) and indeed got `ghcide` to _sort of_ work with the LH plugin. I say "sort of" because we were observing some strange behaviour where diagnostics would be …
> Allow GHC plugins to be called with an updated StringBuffer

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Plugin/Completions.hs
This is a straightforward fix that came up during https://github.com/haskell/haskell-language-server/pull/191
> Populate ms_hs_date in GetModSummary rule

- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Spans/AtPoint.hs
- src/Development/IDE/Spans/Common.hs
- src/Development/IDE/Spans/Documentation.hs
- test/exe/Main.hs
Currently this only searches local documentation (generated with
`cabal haddock --haddock-hyperlink-source` or equivalent) but could be
extended to support searching via Hoogle in the future. And it works for
any of the core libraries since they come installed with documentation.
Will show up in hover and completions.
Also fixes extra markdown horizontal rules being inserted with no
content in between them.
https://streamable.com/59l6zo
The above example needs a patched version of the vscode plugin to open the url inside vscode, but hopefully other clients will be able to handle the link fine
> Add links to haddock and hscolour pages in documentation

- .azure/linux-stack.yml
- .azure/windows-stack.yml
With the repo now officially transferred from Digital Asset's control to the open-source Haskell organization, there is no good reason for master builds to ping DA anymore. This (the corresponding Slack token "secret") is also the only piece of non-open-source configuration in the existing build process, so it needs to be removed before the CI can be transferred.
> CI: remove (internal) DA Slack notifications

- README.md
- exe/Main.hs
- ghcide.cabal
- hie.yaml
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/Import/DependencyInformation.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Notifications.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
It is useful to show diagnostics for all files in a project when it is initially loaded.
It is also useful to propagate changes we make in one file to other files which depend on the file we have changed. We only trigger this on saves to avoid annoying users with a barrage of errors, which is also helpful for IDE speed and responsiveness as we don't want to potentially recompile the entire project on every keystroke.
This reduces dependence on `kick`, as we can precisely target the files we need to reload.
Also fixed a bug where we would cache the iface of a file that compiled due to `-fdefer-type-errors`. Due to this, on subsequent runs of `ghcide`, we would not get diagnostics for those files. This is also essential to make the parent type-checking stuff work as expected.
> Typecheck entire project on Initial Load and typecheck reverse dependencies of a file on saving

- exe/Main.hs
Currently log level is set to `minBound` regardless of `argsVerbose`. This prints too much stuff when running test mode on a large repo.
> Use argsVerbose to determine log level in test mode

- src/Development/IDE/Spans/Documentation.hs
- test/exe/Main.hs
Part of the fix for haskell/haskell-language-server#247
Windows understands only file:/// but not file:// (at least it's true for VS Code)
> Generate doc file URL via LSP (to fix it for Windows)

- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/CodeAction/PositionIndexed.hs
- test/exe/Main.hs
By generalizing code action: suggestions of delete unused **top** binding to suggestions of delete unused binding.
This is basically a reimplementation which traverses the AST.
> Fix issue #710: fix suggest delete binding 

- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Preprocessor.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Util.hs
- test/exe/Main.hs
> Ignore -Werror

- ghcide.cabal
```
16:18 <maralorn> Should I expect any trouble when building current ghcide (hls-3 branch to be precise) with hie-bios 0.7.0?
16:19 <maralorn> Apparently it does compile without issues.
16:21 <fendor> maralorn, no, the breaking change is in the config type, which neither hls nor ghcide explicltly use
16:21 <fendor> so, everything should just work fine for both these projects
```
I tested. This builds with newest hie-bios for me.
> Bump bounds of hie-bios for 0.7.0

- ghcide.cabal
- src/Development/IDE.hs
A single module to reexport all the commonly used names to simplify the use of ghcide as a library
> Add a module Development.IDE

- session-loader/Development/IDE/Session.hs
We use a multi-project bios cradle at work, and currently the progress message is always the same "Setting up project fbcode", which isn't very helpful. This simple change will help at least determine what prompted the cradle call
> Include module path in progress message

- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
When parsing a module, if parsing haddocks succeeds, then use them
Previously, even though we were parsing modules twice, with and without
haddocks, we were just returning the result of parsing without haddocks.
The reason for this was that Opt_KeepRawTokenStream and Opt_Haddock do
not interact nicely. We decided that for now it was better to fix an
actual issue and then solve the problem when hlint requires a module
with Opt_KeepRawTokenStream.
> Show documentation on hover for symbols defined in the same module

- exe/Main.hs
- src/Development/IDE/LSP/LanguageServer.hs
- test/data/rootUri/dirA/Foo.hs
- test/data/rootUri/dirA/foo.cabal
- test/data/rootUri/dirB/Foo.hs
- test/data/rootUri/dirB/foo.cabal
- test/exe/Main.hs
Pass the `config` param to `runLanguageServer` so that we can extract the directory from `InitializeRequest`. 
Fixes https://github.com/digital-asset/ghcide/issues/646
> Use InitializeParams.rootUri for initial session setup

- session-loader/Development/IDE/Session.hs
This fixes the issue on Linux where the binary was statically linked and Template Haskell (or the eval plugin on haskell-language-server) tried to evaluate some code. It would previously fail to load ghc-prim because it couldn't lookup symbols from libm which are usually dynamically linked in.
See https://github.com/haskell/haskell-language-server/issues/221
Unfortunately we can't just statically link in `libm` and have the binary `dlsym` on itself apparently: https://stackoverflow.com/questions/14289488/use-dlsym-on-a-static-binary
So now the statically linked binary actually dynamically links in `libm` on a "best-effort" case: From what I can tell if `libm` is not available this will just print an error to stderr and carry on as usual (albeit it will trip up on Template Haskell), and if …
> Dynamically load libm on Linux for each new session

- ghcide.cabal
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/CodeAction/RuleTypes.hs
- src/Development/IDE/Plugin/CodeAction/Rules.hs
- src/Development/IDE/Types/Exports.hs
- test/data/hover/GotoHover.hs
- test/exe/Main.hs
Fixes #737. Requires #688 to be merged first.
> Suggestions for missing imports from local modules

- src/Development/IDE/Spans/Common.hs
> Fix haddock to markdown conversion (attempt 2)

- .azure/windows-stack.yml
* As @wz1000 has noted, the windows job is failing lately due to the actual 60 minutes timeout, increased to 120
> Increase timeout of azure windows job

- .ghci
- ghcide.cabal
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Types/Action.hs
- test/data/boot/hie.yaml
- test/exe/Main.hs
This improves on the single thread pumping user actions right now
> Handle multiple user actions concurrently

- src/Development/IDE/Core/FileStore.hs
Should fix https://github.com/haskell/haskell-language-server/issues/181 in most cases
> Don't typecheck parents when there are no known files

- ghcide.cabal
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Types/Options.hs
- test/exe/Main.hs
> Refinement holes

- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Types/Exports.hs
It was appending lists of identifiers without pruning duplicates
Fixes #771 
```
pepeiborra@pepeiborra-mbp w1 % column -t -s , bench-hist/results.csv
version    name                         success   samples   startup              setup                experiment           maxResidency
upstream   hover                        True      100       10.822233228         0.0                  2.436788999          582MB
upstream   edit                         True      100       9.478771113          0.0                  35.664150921         600MB
upstream   getDefinition                True      100       9.838020262          0.0                  2.5956575830000004   587MB
upstream   hover after edit             True      100       11.241869796000001   0.0                  5.150880557000001 …
```
> Fix bug in exports map

- .azure/linux-bench.yml
- .gitignore
- README.md
- azure-pipelines.yml
- bench-hist/.artifactignore
- bench/README.md
- bench/hist.yaml
- bench/hist/Main.hs
- Remove the stack.yaml assumptions
- Remove the `upstream/master` git branch assumption, just use `master` instead
- Add a configuration setting to select build tool, make Cabal the default now (previously stack was required)
- Add a CI job
Fixes #747
> Improve hist benchmarks driver and add to CI

- exe/Main.hs
- ghcide.cabal
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/Plugin/CodeAction.hs
- src/Development/IDE/Plugin/Test.hs
- src/Development/IDE/Types/Action.hs
- stack-ghc-lib.yaml
- stack.yaml
- stack810.yaml
- stack84.yaml
- stack88.yaml
- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
#727 made the Shake queue able to concurrently handle more than one rule, but ghcide still handled LSP requests sequentially. This change makes the LSP handler multi-threaded, so now ghcide no longer blocks while e.g. computing an expensive code lens.
This change also adds a custom request protocol for testing, which can be generally useful. For instance, tests can now query the location of the interface files cache dir which will be useful for testing #760
Reviewers - things to watch for:
- New space leaks
- New race conditions
To do:
> Fully asynchronous request handling

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
Closes #671 
Only manual testing done, yet. Not sure how this can be tested, suggestions welcome!
> Save source with HIE files

- exe/Main.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/LSP/Notifications.hs
- test/exe/Main.hs
To achieve this we augment the FileOfInterest store with a flag that indicates whether a file is saved on disk or not.
> Write ifaces on save

- .azure/linux-stack.yml
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Orphans.hs
- src/Development/IDE/GHC/Util.hs
- src/Development/IDE/Import/FindImports.hs
- test/exe/Main.hs
I noticed ghcide HEAD was broken on the ghcide submodule of the haskell-language-server repo, after the recent changes to import paths. Hopefully this fixes the issue
Fixes #780
> Import paths are relative to cradle

- ghcide.cabal
Ideally we would do this with a Cabal flag, but I don't think it is possible
to disable optimisation only for the tests stanza
> Disable optimisation in tests

- .azure/linux-stack.yml
- src/Development/IDE/Core/FileStore.hs
- test/exe/Main.hs
This test failure did hide a real bug after all. We need to type check all the parents of the modified file, restricted to the files of interest. That's precisely what kick does.
> Fix setFileModified and restore test

- src/Development/IDE/Core/PositionMapping.hs
- test/exe/Main.hs
We sometimes need to know the original range that a position mapped to, when a simple failure is not helpful.
For example, when the user is typing inside a do block, we would like to use position mapping to tell us that the current cursor position is within the span of the do block, where the span is known from the old version of the file for which we have compiler artifacts. This can be helpful for things like generating completions based on local variables.
> Extend position mapping with fuzzy ranges

- .azure/windows-stack.yml
- cabal.project
- ghcide.cabal
- session-loader/Development/IDE/Session.hs
- stack.yaml
- stack810.yaml
- stack8101.yaml
- stack84.yaml
- stack88.yaml
* The test suite hangs in my windows 10 😟 
* I've tried several projects without hie.yaml and seems to work fine
//cc @Avi-D-coder
> Use implicit-hie when no explicit hie.yaml

- .azure/linux-bench.yml
- .azure/linux-stack.yml
- .azure/windows-stack.yml
- azure-pipelines.yml
Not needed when we had a successful cache hit, saves ~ 2 minutes
> Skip unnecessary packing of cache artifacts

- ghcide.cabal
I removed `-threaded` from the test binary ghc options recently. 
Without it lsp-test no longer times out, and tests get stuck instead of failing with a helpful error message
> Restore -threaded

- src/Development/IDE/LSP/Notifications.hs
- test/exe/Main.hs
Initially I thought I would check if the file exists on disk, but then I realized that vscode violates our assumptions anyway, so we should mark it as `Modified` to be safe.
> Mark files as modified on open

- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
Fixes #613 and [#342](https://github.com/haskell/haskell-language-server/issues/342) at haskell-language-server.
> Fix import suggestions when dot is typed

- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
The problem we are trying to solve is accurately decide what modules belong to a cradle when there are multiple projects sharing the same source folder, and project membership is driven by a Bios cradle. 
For instance, say we have modules A,B,C in the same folder, and A,B should use the same set of flags whereas C should use a different set of flags. For A or B, the Bios cradle will return the set of flags F1 and the targets {A,B}. For C, the Bios cradle will return the set of flags F2 and the set of targets {C}. 
While editing A, when finding an `import C`, ghcide must not allow ghc to load `C`, and instead must locate it in a package. 
The improvement in this PR is to preserve more information from the set of targets returned by the cradle. Targets can be either file paths or modules. …
> Preserve more information about targets

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/GHC/Compat.hs
- test/data/THNewName/A.hs
- test/data/THNewName/B.hs
- test/data/THNewName/C.hs
- test/data/THNewName/hie.yaml
- test/exe/Main.hs
This fixes part of #614 by introducing a workaround for ghc droping some bindings that we still need.
> Restore identifiers missing from hi file

- src/Development/IDE/Spans/Documentation.hs
Below is an example when documentation is available but wasn't located because file name is less specific than module. This PR fixes it
**Documentation:**
Note the difference in doc file name and module name.
**Source:**
In this case both src and module name are the same.
**Other notes:**
* Also all directories attempted (not sure if it can possibly be more than one directory but original code is trying only first anyway)
* Just in case I'm on Windows (10)
* I'm experiencing more troubles with docs/sources on Windows (docs for most libs reported to be at $topdir/../ which doesn't work on Windows) but let's tackle one thing at a time.
* using stack
> Fix documentation (or source) link when html file is less specific than module

- .azure/linux-bench.yml
- cabal.project
- src/Development/IDE/Core/IdeConfiguration.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Notifications.hs
- test/exe/Main.hs
* The motivation is to expose the client settings in shake rules, concretely my goal is to enable or disable [hlint diagnostics](https://github.com/haskell/haskell-language-server/pull/166) using a client setting, changing diagnostics on the fly if the user change it in the editor
* I hope being able to configure the rules (when parsing or typechecking for example?) using the client settings could be useful in general
*  The config is stored in the json raw format and updated using the `InitializeParams` and the `didChangeConfigurationParamsHandler` notification
* The first one is empty using vscode, it notifies a configuration change when the lsp server is started. I guess other editors will use the first one (???). I assume both should update the client settings cause the …
> Store the lsp client settings in shakeExtras and create a Rule to get them

- src/Development/IDE/Core/Compile.hs
- test/data/hover/GotoHover.hs
- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
This patch uses the new "unnecessary" or "deprecated" tags for diagnostics to show unused variables/functions/... dimmed in the editor, as discussed in https://github.com/haskell/ghcide/issues/165#issuecomment-692532054
> Tag unused warning as such

- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
To run the test suite in parallel with Cabal:
> cabal test --test-options="+RTS -N"
Locally, this runs in 58s in a Xeon with 56 logical cores
Importantly, this does not change CI
(unless stack passes +RTS -N secretly)
> Enable test suite to run in parallel

- ghcide.cabal
- shell.nix
- src/Development/IDE/Core/FileExists.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/LSP/LanguageServer.hs
- src/Development/IDE/LSP/Notifications.hs
- test/exe/Main.hs
This is broken. It sends an illegal message before we've sent the initialize response. I got this far because (amusingly) it actually works in emacs, but the test suite complains.
I'm not sure quite how to fix this. @pepeiborra suggested sending the message in `fileExistsRules` as I'm doing, but this appears to happen too early.
I can think of a few gross ways to fix this (actually do the registration the first time `GetFileExists` runs, add some extra state to determine whether we've done it), but I thought I'd put it up to solicit ideas.
------
This prevents us from sending thousands of notifications to the client
on startup, which can lock up some clients like emacs. Instead we send
precisely one.
This has some consequences for the behaviour of the fast file existence
lookup, which …
> FileExists: set one watcher instead of thousands

- .azure/windows-stack.yml
- cabal.project
- ghcide.cabal
- stack.yaml
- stack810.yaml
- stack8101.yaml
- stack88.yaml
- test/exe/Main.hs
* Failing tests are marked with `knownBrokenInWindows` until they get fixed: see #474
* Enable test suite in azure
* It needs a `lsp-test` hackage release with the fix to avoid hangs in windows (/cc @bubba)
> Enable test suite in Windows, marking failing tests as broken

- .azure/windows-stack.yml
1. Rerun only the failing tests
2. Rerun only the failing tests and produce an LSP log for diagnosis
> Rerun Windows tests just like linux tests

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
I'm trying to fix [this issue](https://github.com/haskell/haskell-language-server/issues/360), which is quite relevant for our codebase at work: we have many type signatures like this, for which the code action `"Add CONSTRAINT to the context of the type signature for FUNCTION"` doesn't work.
```haskell
someFunction
:: ( WithDb env m
, WithError m
, Has PieceOfConfig env
)
=> Id User
-> Id ProjectInfo
-> m ProjectInfo
someFunction userId projectId = do
...
```
I added 2 failing tests illustrating both issues. The current implementation seems quite brittle (based on parsing stuff with regexes), I'm trying to figure out how to make it more robust..
> Fix code action for adding missing constraints to type signatures

- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/GHC/Orphans.hs
- src/Development/IDE/Import/DependencyInformation.hs
- src/Development/IDE/Import/FindImports.hs
- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Spans/AtPoint.hs
- src/Development/IDE/Spans/Common.hs
- src/Development/IDE/Spans/Documentation.hs
- src/Development/IDE/Types/Exports.hs
- test/exe/Main.hs
Rework of https://github.com/mpickering/ghcide/pull/43/
Should improve performance and also functions as a workaround for #614 
We now generate object code along with the interface file. Object code is only generated for a module if
1) The module uses TH
2) Any parents of the module use TH
For this to work, we require the complete module graph. Earlier, tests were failing because `TargetFile`'s were not included in the set of known files. I fixed this, but now tests are failing because the modules don't define a `main` function. Any idea why this is happening @pepeiborra? See my last commit.
FIxes #614 
Fixes #107
> Use object code for Template Haskell

- src/Development/IDE/LSP/Notifications.hs
This gets quite noisy when cabal is building dependencies which makes it
hard to see what's going on.
> Downgrade file watch debug log to logDebug from logInfo

- src/Development/IDE/Spans/AtPoint.hs
- src/Development/IDE/Spans/Common.hs
- test/data/hover/GotoHover.hs
- test/exe/Main.hs
Fixes #847 
This PR solves both problems:
- It contains a regular expression to catch internal names for holes `/_[^_]*_.....?/` and rewrite them to `_`,
- It ensures that "no location info" is not shown by filtering out "unhelpful locations"
> Do not show internal hole names

- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/GHC/Util.hs
The Eval plugin in hls needs to retrieve the import paths from the value returned by the `GhcSessionDeps` rule. 
More details in https://github.com/haskell/haskell-language-server/pull/488
> Preserve envImportPaths in GhcSessionDeps

- src/Development/IDE/GHC/Util.hs
- test/exe/Main.hs
This is a bug fix that only applies when using file targets with symlinks. The locate imports logic performs an equality check for file targets and import dirs, and this goes wrong currently since we only canonicalise file targets, but not import dirs.
> Canonicalize import dirs

- src/Development/IDE/Types/Diagnostics.hs
With the current implementation, VS Code will show "1:1" for the top
left corner, but the pretty printer renders this poisition to "1:0".
This is particularly interesting for people building command line tools
using `ghcide`, like the our DAML compiler at Digital Asset.
tools with command line drivers, like us at Digital Asset.
I would argue that VS Code has the ultimate authority on this since we
can't change what it displays without also moving the squiggly lines.
This PR fixes the discrepance by simply adding one to the column number
in the prtty printer, like we do for the line number.
> Fix pretty printer for diagnostic ranges

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
This PR implements https://github.com/haskell/haskell-language-server/issues/339. The code removing single redundant import can be reused.
> Add code action for remove all redundant imports

- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/GHC/Compat.hs
- src/Development/IDE/Plugin/Completions.hs
- test/exe/Main.hs
I think this is the best option left now.
There are a couple of feasible alternatives I can think of:
1. Use a hybrid strategy, using object code the first time we compile and bytecode all subsequent times. This should be easy to implement after this PR, it would require just a two line change in `getLinkableType`. We can also generate object code (but not use it) on save. This will hopefully result in faster startup and less memory usage at boot, but as files are changed, memory usage will quickly climb to and surpass the bytecode only strategy (since the object code will be loaded in and we can't unload it).
2. I think it should be possible to serialize core to iface files, taking hints from https://github.com/ezyang/ghc/commit/13615ca4e4bf759f323de22a3d182b06c4050f38. For this scheme …
> Switch back to bytecode

- test/exe/Main.hs
Recently, we fixed a bug in `prettyRange` where lines where rendered
1-based but columns 0-based. Let's make sure we don't get into such
weird situations again by adding a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/haskell/ghcide/878)
> Add a test to check diagnostic ranges are printed 1-based

- session-loader/Development/IDE/Session.hs
This is in response to a [reddit post](https://www.reddit.com/r/haskell/comments/jg9h6r/what_does_no_cradle_found_for_proceeding_with/) about the warning.
> Clarify and downgrade implicit-hie message

- src/Development/IDE/Core/Compile.hs
- src/Development/IDE/Core/Rules.hs
We can re-use the modsummary when we parse, don't need to generate a new one.
> Simplify and deduplicate ModSummary logic

- .azure/linux-bench.yml
- azure-pipelines.yml
- bench/hist/Main.hs
It appears that the benchmark suite gets stuck due to `stack exec` grabbing a file lock that it didn't use to. 
This PR is to debug the issues to try find a fix or workaround
```
ghcide> still blocking for directory lock on /home/vsts/work/1/s/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build-lock; maybe another Stack process is running?
ghcide> still blocking for directory lock on /home/vsts/work/1/s/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build-lock; maybe another Stack process is running?
ghcide> still blocking for directory lock on /home/vsts/work/1/s/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build-lock; maybe another Stack process is running?
```
> Disable CI benchmark suite

- ghcide.cabal
* To make available instances downstream
* Needed to use ghcide master in hls: https://github.com/haskell/haskell-language-server/pull/568
> Expose Development.IDE.GHC.Orphans

- exe/Main.hs
- session-loader/Development/IDE/Session.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/OfInterest.hs
- src/Development/IDE/Types/Options.hs
This change leverages that rules are rerun by shakeRunDatabase.
It allows users of ghcide as a library to use their own kick
> Avoid calling kick explicitly

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
A tiny fix to export operators properly. If I understand correctly, identifiers can be either totally symbolic or alpha num. And it might be safe to use `type ...` in the export list:
> The extension -XExplicitNamespaces is implied by -XTypeOperators and (for some reason) by -XTypeFamilies.
we could define those operators only when TypeOperators is enabled.
Closes haskell/haskell-language-server#589. Perhaps I should add some tests :)
> Parenthesize operators when exporting

- stack-windows.yaml
- stack.yaml
* In my machine stack finds a build plan without allow-newer, let's see what have to say ci
> Remove allow-newer

- src/Development/IDE/Core/Compile.hs
- test/exe/Main.hs
This is the result of the discussion in https://github.com/haskell/haskell-language-server/issues/572. As such, it closes #902 and supersedes it. Most of the warnings are anyway enabled by `-Wall`, which is taken as a good practice in the community.
@georgefst @jneira you might be interested in this.
> Do not enable every "unnecessary" warning by default

- session-loader/Development/IDE/Session.hs
- test/data/cabal-exe/a/a.cabal
- test/data/cabal-exe/a/src/Main.hs
- test/data/cabal-exe/cabal.project
- test/data/cabal-exe/hie.yaml
- test/exe/Main.hs
The filetargets are not correctly absolute. The hie-bios API did not articulate it correctly. 
So, in certain cases, the following error is shown for file-targets in sub-directory:
```
/tmp/extra-dir-30793437515428/src/Main.hs: openBinaryFile: does not exist (No such file or directory)
```
Adds a test that this was the case and is now fixed.
> Make Filetargets absolute before continue using them

- README.md
Add a link to the vscode extension, and minor cleanup.
> Clean up some of the linky-links in the README

- exe/Main.hs
- session-loader/Development/IDE/Session.hs
When using ghcide as a library, it may be desirable to host the hie.yaml file
in a location other than the project root, or even avoid the file system altogether
> Custom cradle loading

- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Import/DependencyInformation.hs
Fixes #921.
Done: `transitiveReverseDependencies` and `immediateReverseDependencies` have been refactored to return `Maybe [...]`.
I haven't changed `reportImportCyclesRule` or `transitiveDeps` as they seem to be acquitted in https://github.com/haskell/ghcide/issues/921#issue-749520646, although I can't say that I personally understand the logic there.
TODO: Predictably these types changing has stirred up type errors elsewhere. Although there are obvious workarounds, I'm not familiar with the desired behavior for these call sites to propose just converting `Nothing` -> `[]`.
https://github.com/haskell/ghcide/blob/30a46e8a18263c7b76384b854f40b21e6e88f7ba/src/Development/IDE/Core/FileStore.hs#L245
I imagine this should error out if we fail to get the reverse dependencies? If so, what's the …
> Favor `lookupPathToId` over `pathToId`

- src/Development/IDE/Plugin/Completions.hs
- src/Development/IDE/Plugin/Completions/Logic.hs
- src/Development/IDE/Plugin/Completions/Types.hs
- test/exe/Main.hs
Address #576 requirement of automatically extending the import list.
Few points to address (and I would like some pointers on this)
Simple working Demo
Items to address:
```
import Control.Monad as M (
join,
msum)
```
This PR  adds the new item to the last item like this:
```
import Control.Monad as M (
join,
msum, mplus)
```
Demo:
> Extend import list automatically

- .hlint.yaml
- bench/config.yaml
- bench/hist/Main.hs
- bench/lib/Experiments.hs
- bench/lib/Experiments/Types.hs
- cabal.project
- fmt.sh
- ghcide.cabal
- hie.yaml
- nix/default.nix
- shake-bench/LICENSE
- shake-bench/shake-bench.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
- shell.nix
- stack.yaml
There's some room for reusing the rules used in the historic benchmarking suite
in other projects. This change makes that a bit easier and improves the
documentation and code structure.
The new structure is:
- `lib:shake-bench` - a Cabal library with functions to generate Shake rules
- `ghcide:bench:benchHist` - the ghcide instantiation of the above Shake rules
That's not to say that `shake-bench` is completely decoupled from ghcide -
there are still plenty of assumptions on how the benchmarks are organized, their
outputs, etc. But with a little bit more effort it should be easy to make
these rules more reusable
> Extract the benchmarking Shake rules to a standalone Cabal package

- src/Development/IDE/Plugin/CodeAction.hs
- test/exe/Main.hs
#916 was tricky and didn't work in some cases. Now the procedure has become clearer, and I add some comments to show how it works. I'm not sure all cases are covered, and we may need more tests.
> Cleanup addBindingToImportList

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
- src/Development/IDE/Plugin/Completions/Logic.hs
* It fixes the build for ghc-8.8.3 and ghc-8.8.2 that was failing with:
```
Progress 166/173: ghcide ghcide > /root/build/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs:267:5: error:
Progress 166/173: ghcide ghcide >     • Illegal equational constraint NoGhcTcPass pass
Progress 166/173: ghcide ghcide >                                     ~ NoGhcTcPass (NoGhcTcPass pass)
Progress 166/173: ghcide ghcide >       (Use GADTs or TypeFamilies to permit this)
Progress 166/173: ghcide ghcide >     • When checking the inferred type
Progress 166/173: ghcide ghcide >         f :: forall (pass :: Pass).
Progress 166/173: ghcide ghcide >              (Outputable.OutputableBndr
Progress 166/173: ghcide ghcide >                 (NameOrRdrName (IdP (GhcPass (NoGhcTcPass pass)))),
Progress 166/173: …
```
> Use GADTs for all ghc versions in Development.IDE.Plugin.Completions.Logic

- exe/Main.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Core/Tracing.hs
- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
Reworked version of #943. The root problem was in the use of stale data in rules - after adding a missing import the `GetDependencies` rule would fail, but `TypeCheck` would go ahead anyway with the last successful result of `GetDependencies` and generate a missing module diagnostic which duplicates the one already generated by `GetDependencies`.
In general it seems a very bad idea to use stale data in core rules, if only because it makes it very difficult to reason about diagnostics. I have removed all other uses I've seen. 
While I was debugging this with the command line driver, I found the default options to check all targets very noisy, and I changed the defaults (for the command line driver only). Moreover, I added tracing of rule failures.
Fixes haskell/haskell-language-server#630
> Deduplicate module not found diagnostics

- ghcide.cabal
In an effort to move Completions into its own hls-plugin package we have a dependency to access the getDocumentation function exposed in this module. Therefore, can we expose this module so that we will be able to access that function.
> Expose Documentation module

- bench/lib/Experiments.hs
- exe/Arguments.hs
- exe/Main.hs
- ghcide.cabal
- src/Development/IDE.hs
- src/Development/IDE/Core/FileStore.hs
- src/Development/IDE/Core/RuleTypes.hs
- src/Development/IDE/Core/Rules.hs
- src/Development/IDE/Core/Service.hs
- src/Development/IDE/Core/Shake.hs
- src/Development/IDE/Plugin/Test.hs
- test/exe/Main.hs
- test/src/Development/IDE/Test.hs
Given a FOI F with non null typechecking diagnostics D, imagine the following scenario:
1. An edit notification for F is received, creating a new version
2. GetModTime is executed, producing 0 diagnostics.
2.1 updateFileDiagnostics is called
2.2 setStageDiagnostics is called
2.3 LSP.updateDiagnostics is called with a new version, resetting all the
diagnostics for F
2.4 newDiags=[] in updateFileDiagnostics, which is different from D (the last
published diagnostics), which enqueues a new publishDiagnostics [] in the
Debouncer
3. An edit notification for F is received before typechecking has a chance to
run which undoes the previous edit
4. The debouncer publishes the empty set of diagnostics after waiting 0.1s
5. GetFileContents runs and since the contents of the file haven't changed since …
> Fix diagnostics update bug

- CHANGELOG.md
- ghcide.cabal
- src/Development/IDE/Plugin/Completions/Logic.hs
- test/exe/Main.hs
This is a point release to disable the auto extend import snippets from completions because of the issues reported in https://github.com/haskell/haskell-language-server/issues/679
> Prepare release 0.6.0.2
