haskell/ghcide

exe/Main.hs, src/Development/IDE/Core/RuleTypes.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/GHC/Orphans.hs, src/Development/IDE/GHC/Util.hs, src/Development/IDE/Types/Options.hs
Following on from https://github.com/digital-asset/daml/pull/2808, here is the rebased version.
=> Add multi environment support

README.md
Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
minor fix of correct path.
=> building extension in correct path

extension/package.json, src/Development/IDE/Core/Compile.hs, src/Development/IDE/Types/Options.hs, test/manual/lhs/Bird.lhs, test/manual/lhs/Main.hs, test/manual/lhs/Test.lhs
Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
here I am again with the changes for literate Haskell support in `ghcide`.
=> added unlit stage for literate Haskell source files

azure-pipelines.yml
Done blind, but from local experiments.
=> #26, test GHC 8.4

README.md
Instructions to setup https://github.com/neoclide/coc.nvim and neovim
together with ghcide.
=> Added setup instructions for vim/coc to README

README.md
This is a certainly incomplete list of features already implemented. Please expand!
=> Add feature list

exe/Main.hs, src/Development/IDE/GHC/Compat.hs, stack-ghc-lib.yaml, stack.yaml, stack84.yaml
=> Build on GHC 8.8

src/Development/IDE/Core/Shake.hs, src/Development/IDE/LSP/CodeAction.hs
fixes #79 which also contains a detailed description of the issue.
cc @ndmitchell
=> Fix race condition in shakeRun

stack-ghc-lib.yaml, stack.yaml, stack84.yaml
=> bump to hie-bios 0.2.0 and bump *lsp packages

ghcide.cabal
=> Add a lower bound on hie-bios

README.md
I hope i am not doing this in too small steps …
Let me just say how much I enjoy working with ghcide. It works marvelously!
Thanks to everyone how works on this.
=> Add type signature inserting to feature list

exe/Main.hs
As @mpickering mentions in #99, initializeFlagsWithCradle is not the right API, as it does a downsweep and a load, which we don't need.
If we take our `hie.yaml` for `ghcide` and add `Main` as an argument (which is roughly what things like Cabal/Stack cradles will produce) it drops the running time from 8.3s to 4.3s - so probably provides a significant speed benefit at startup time in many projects. Might also reduce memory, but I didn't bother testing.
=> Use the hie-bios function that doesn't perform a downsweep. Fixes #99

src/Development/IDE/Core/Rules.hs
This function is never used in ghcide so it makes more sense to have
it be part of the `daml` source code since we depend on this for
building the `.dar` archives.
=> Remove writeIfacesAndHie

hie.yaml
Now we use Paths_ghcide it's important that hie.yaml can find them.
=> Fix hie.yaml so it works

azure-pipelines.yml, stack88.yaml
Required no changes, but useful to keep it working.
=> Add tests for GHC 8.8

README.md, docs/Setup.md
A few common issues. Not intended to be comprehensive, but if we always answer setup questions on this page and then reference them from the issues, eventually it will become comprehensive.
=> #129, add a very basic setup guide

test/exe/Main.hs
+ Reduce manual duplication of information shared between hover and
goto-def tests
+ Make sure that all the information in the test specifications that
relates to fiddly line and column numbers, fits together on one
screen, and is generally easier to match and understand by eye.
=> Refactor goto-definition and hover tests

src/Development/IDE/LSP/LanguageServer.hs, test/exe/Main.hs
Following on from the conversation in #147 ...
=> Signal code actions in initialize response

stack88.yaml
=> More things are in the latest stack snapshot

test/exe/Main.hs
Add *go to defirition* and *hover* tests for type constructors which are defined in a different package. This adds a new row, *external type constructor*, to the table from #139:
| | find definition | hover |
|-------------|-----------|---------|
| field in record definition | :heavy_check_mark:  | :heavy_check_mark: |
| field in record construction | :x:  | :x: |
| field name as accessor | :heavy_check_mark: | :heavy_check_mark: |
| top level name | :heavy_check_mark: | :heavy_check_mark: |
| record data constructor | :x: | :x: |
| plain data constructor | :heavy_check_mark: | :heavy_check_mark:  |
| type constructor | :heavy_check_mark: | :x: |
| external type constructor | :heavy_minus_sign: | :x: |
| plain parameter | :heavy_check_mark: | :heavy_check_mark: |
| pattern match name | …
=> Add goto/hover tests for type constructors from other package

exe/Main.hs, extension/package-lock.json, extension/package.json, extension/src/extension.ts, ghcide.cabal, src/Development/IDE/Core/Service.hs, src/Development/IDE/Core/Shake.hs, src/Development/IDE/LSP/Definition.hs, src/Development/IDE/LSP/Hover.hs, src/Development/IDE/LSP/LanguageServer.hs, src/Development/IDE/Types/Options.hs, stack-ghc-lib.yaml, stack.yaml, stack84.yaml, stack88.yaml, test/exe/Main.hs
This is only a draft since my patch to `haskell-lsp` isn’t finished yet but it seems to work in my very limited testing.
=> Fix progress reporting

src/Development/IDE/Core/Rules.hs
We would like to use the rule without caching its artifacts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/digital-asset/ghcide/179)
=> Provide the body of the GenerateCore rule as a standalone function

README.md
...using its default configuration layers
=> Add configuration example for SpaceVim

azure-pipelines.yml
This should hopefully fix CI. Not quite sure what Azure messed
up. This happened on several repositories.
=> Force cache refresh

src/Development/IDE/Core/Compile.hs, src/Development/IDE/Core/FileStore.hs, src/Development/IDE/Core/OfInterest.hs, src/Development/IDE/Core/RuleTypes.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/Core/Service.hs, src/Development/IDE/Core/Shake.hs, src/Development/IDE/Types/Location.hs, src/Development/IDE/Types/Options.hs
This is intended for the DAML CLI compiler which is also built upon
`ghcide`. For now, we have no intention of using this in the DAML IDE
or in ghcide but that might change in the future.
See https://github.com/digital-asset/daml/pull/3378 for the corresponding DAML PR.
=> Infrastructure for on-disk incremental builds

stack88.yaml
My monthly PR pursuing the goal of getting ghcide in Stackage. I've also raised https://github.com/bubba/lsp-test/issues/60 and https://github.com/haskell-hvr/hslogger/issues/55 to see if we can encourage the dependencies to be added.
=> Reduce stack.yaml differences

docs/Setup.md
Just copying and pasting the advice.
=> #208, document the proposed solution

test/data/GotoHover.hs, test/exe/Main.hs
=> Add tests for #274: literals in hover info

src/Development/IDE/Spans/AtPoint.hs
Name of the arguments didn't match with types
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
=> Swapped argument names

README.md
=> Readme: Consistent language server command

stack88.yaml
Now down to one. I've ping'd that library to try and get it on Stackage, and then we could get back on Stackage. https://github.com/joom/fuzzy/issues/1
=> Reduce the number of Stackage overrides

ghcide.cabal, src/Development/IDE/GHC/Error.hs
=> Add Development.IDE.GHC.Error to the public API

src/Development/IDE/Spans/Calculate.hs, test/exe/Main.hs
=> Support more kinds of literals in hover

src/Development/IDE/Core/Compile.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/GHC/CPP.hs, src/Development/IDE/GHC/Util.hs, src/Development/IDE/LSP/Outline.hs, src/Development/IDE/Plugin/CodeAction.hs, src/Development/IDE/Plugin/Completions/Logic.hs
A few changes to support GHC 8.10.
Relies on:
- `haskell-lsp-types` PR https://github.com/alanz/haskell-lsp/pull/213
- `hie-bios` PR https://github.com/mpickering/hie-bios/pull/134
=> GHC 8.10 support

src/Development/IDE/GHC/Util.hs
Shoving up for some CI love, and also needs some manual testing locally (which I'm starting now). @mpickering in #360 tries to delete fakeDynFlags. If it works, that's a nice simplification.
=> See if fakeDynFlags is unnecessary

src/Development/IDE/Core/Compile.hs
This is a correctness fix to consider the dflags configuration.
It a spinout from the effort to switch to interface files (#355)
=> Fix ModLocation creation

src/Development/IDE/Core/FileStore.hs
Do we not have Windows CI? I ran into this locally when trying to build.
=> Fix build on Windows

stack88.yaml
I added fuzzy. so now we're down to no non-Stackage deps.
=> Move to the latest Stackage snapshot

exe/Main.hs, src/Development/IDE/Core/IdeConfiguration.hs, src/Development/IDE/LSP/HoverDefinition.hs, src/Development/IDE/LSP/LanguageServer.hs, src/Development/IDE/LSP/Notifications.hs, src/Development/IDE/LSP/Outline.hs, src/Development/IDE/LSP/Server.hs, src/Development/IDE/Plugin.hs, src/Development/IDE/Plugin/CodeAction.hs, src/Development/IDE/Plugin/Completions.hs
So that haskell-language-server can use its own config
=> Parameterize the haskell-lsp client config type

src/Development/IDE/GHC/Util.hs, src/Development/IDE/Plugin/CodeAction.hs, test/exe/Main.hs
=> Fix add suggested import for operators

src/Development/IDE/Plugin/CodeAction.hs, test/exe/Main.hs
Now guess missing imports also works for:
- Type names
- Data constructors
- Operators
- Qualified things
Avoiding:
- internal modules
ToDo (but not in this PR):
- Things defined in internal modules and then reexported from public ones, like `Typeable`.
- Upfront loading of all modules in package dependencies, to make this code action work consistently out of the box. Currently it only works when the `HscEnv` already has the external modules in the `ExternalPackageState`.
=> Guess more imports

README.md
See https://github.com/digital-asset/ghcide/pull/435#issuecomment-592504569 for context
=> Add a note about hacking on ghcide from Windows

stack84.yaml
Seems to cause problems for users, e.g. #464
=> Try removing allow-newer

exe/Arguments.hs, exe/Main.hs, exe/Rules.hs, ghcide.cabal, src/Development/IDE/Core/Service.hs, src/Development/IDE/Core/Shake.hs, src/Development/IDE/Types/Options.hs, test/exe/Main.hs
Tests to ensure that the cradle loading logic does not regress into calling `runCradle` multiple times per cradle
=> Tests for cradle loading

exe/Rules.hs, src/Development/IDE/Core/FileExists.hs, src/Development/IDE/Core/IdeConfiguration.hs, src/Development/IDE/Core/Shake.hs, test/exe/Main.hs
I noticed these running VSCode + ghcide master on the GHC codebase
=> Fix two regressions since 0.1.0

ghcide.cabal, src/Development/IDE/LSP/Outline.hs, src/Development/IDE/Plugin.hs, src/Development/IDE/Plugin/CodeAction.hs
Also tweak the code action reply type to generate well-formed JSON
=> Expose codeAction and codeLens providers for haskell-language-server

exe/Arguments.hs, exe/Main.hs
=> Expose an option to control the number of Shake threads

src/Development/IDE/Import/DependencyInformation.hs
Clarifies a little whats going on in Development.IDE.Import.DependencyInformation.
=> type alias for FilePathId maps and sets

src/Development/IDE/Core/Shake.hs, test/exe/Main.hs
The HLint bug this used to trigger is now fixed.
=> Remove unnecessary HLint ignores now HLint 3.0.4 is out

src/Development/IDE/Plugin/CodeAction.hs, test/exe/Main.hs
Fixes #539
Doesn't use type information to narrow down suggestions though.
=> Let suggest new imports work on symbol operators used infix

README.md
Let me know if this is too verbose or something is missing. I am happy to reiterate on it. But I hope this can prove useful to others trying to install `ghcide`.
=> Extend nix explanations in README

ghcide.cabal
More breaking changes in the pipeline for ghc-check.
=> Fix upper bounds for ghc-check

src/Development/IDE/GHC/Compat.hs, src/Development/IDE/LSP/Outline.hs, test/exe/Main.hs
By collecting the fieldOcc names in the data con args
=> Add record fields to doucment symbols outline

test/data/Bar.hs, test/data/GotoHover.hs, test/exe/Main.hs
=> Test that GotoHover.hs file compiles in the tests

exe/Main.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/Types/Options.hs, test/exe/Main.hs, test/src/Development/IDE/Test.hs
=> Remove interface loading diagnostics

src/Development/IDE/Core/Shake.hs
I went looking at this wondering if it was a space leak. I never found any evidence of that, but it's also unused, so kill it.
=> Remove the ShakeValue on A

src/Development/IDE/Core/Shake.hs
These error branches should be unreachable. But https://github.com/haskell/haskell-language-server/issues/143 strongly suggests they aren't as unreachable as we'd like! Therefore beef up the error messages if things do go wrong.
=> Improve the error messages around IdeGlobal's

src/Development/IDE/Core/FileExists.hs
Fixes #599. Credit goes to @pepeiborra in #599 who described exactly what to do and why it needs doing. I'm just his typist.
=> #599. register FileExistsMapVar global unconditionally

README.md
Figured out it's not immediately obvious how to produce the benchmarks and graphs that I have been including in my PRs
=> Add a note on differential benchmarks

ghcide.cabal
For use in haskell-language-server plugins
=> Expose GHC.Compat module

ghcide.cabal, src-ghc810/Development/IDE/GHC/HieAst.hs, src-ghc86/Development/IDE/GHC/HieAst.hs, src-ghc88/Development/IDE/GHC/HieAst.hs, src/Development/IDE/Core/Preprocessor.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/GHC/Error.hs, src/Development/IDE/LSP/Outline.hs, src/Development/IDE/Plugin/CodeAction.hs, src/Development/IDE/Plugin/CodeAction/PositionIndexed.hs, src/Development/IDE/Plugin/Completions/Logic.hs, src/Development/IDE/Spans/AtPoint.hs, src/Development/IDE/Types/Location.hs
Some clients don't handle these very well when they are reported for things like definitions etc.
=> Don't report nonsense file names

session-loader/Development/IDE/Session.hs, src/Development/IDE/GHC/Util.hs
=> Preserve import paths for implicit cradles

ghcide.cabal, stack-ghc-lib.yaml, stack.yaml, stack810.yaml, stack84.yaml, stack88.yaml
* To ensure we are able to set the stack.yaml in hie.yaml stack config
=> Use hie-bios-0.7.1

src/Development/IDE/Plugin/CodeAction.hs
=> Sort module import suggestions

session-loader/Development/IDE/Session.hs
The warning links to the hie-bios README and the implicit-hie Hackage page
Closes #788
=> Send a warning when using the implicit cradle

cabal.project, ghcide.cabal, stack.yaml, stack810.yaml, stack8101.yaml, stack84.yaml, stack88.yaml
=> Use implicit-hie-cradle-0.2.0.0

.azure/linux-bench.yml, .azure/windows-stack.yml, azure-pipelines.yml
=> Enable windows ci

.azure/linux-bench.yml, .azure/linux-stack.yml
* The workaround for some issues of the azure cache task is not longer needed so we can save some time and make the script simpler
=> Remove pack/unpack cache from linux jobs

session-loader/Development/IDE/Session.hs
This is a minor correctness fix
=> Use optExtensions in Session loader

test/exe/Main.hs
Tests to demonstrate the current functionality of completions for records.
=> Add completion tests for records.

bench/lib/Experiments.hs, session-loader/Development/IDE/Session.hs, src/Development/IDE/Core/Shake.hs, src/Development/IDE/Plugin/Test.hs
Enhance the benchmark suite to measure user time, delayed work time and allocations.
Fixes bugs I found in the process.
Fixes #703 and is also relevant for #242
=> Enhance benchmarks & bug fixes

docs/Setup.md
=> Update instructions for stty error in windows

ghcide.cabal, stack.yaml, stack810.yaml, stack8101.yaml, stack84.yaml, stack88.yaml
To make progress fixing https://github.com/haskell/haskell-language-server/issues/417
=> Use hie-implicit-cradle-0.2.0.1

bench/config.yaml, bench/hist/Main.hs, bench/lib/Experiments/Types.hs, ghcide.cabal
- Cabal 3.0.0.0 
- haskell-lsp-types 0.22.0.0
=> Run benchmarks on a list of examples 

.azure/linux-bench.yml, bench/hist/Main.hs
Fixes #865 (leaving better visualisations for future work)
=> Interleave and pretty print benchmark results

src/Development/IDE/Plugin/CodeAction.hs
That was my fault :sweat_smile:
=> Fix the bug that "remove all redundant imports" shows everywhere

src/Development/IDE/Core/Compile.hs, src/Development/IDE/Core/RuleTypes.hs, src/Development/IDE/Core/Rules.hs, src/Development/IDE/GHC/Compat.hs, src/Development/IDE/GHC/Orphans.hs, src/Development/IDE/Plugin/Completions.hs, src/Development/IDE/Plugin/Completions/Logic.hs
Calling `tcRnImportDecls` is sufficient
=> Don't need to invoke full typechecking logic for completions

cabal.project, stack.yaml, stack810.yaml, stack8101.yaml, stack88.yaml
with the fix for https://github.com/Avi-D-coder/implicit-hie/issues/17
=> Use implicit-hie-0.1.2.0

ghcide.cabal
New PR to replace previous one that contained spurious commits.
=> Expose Development.IDE.Core.Preprocessor

.azure/linux-stack.yml, include/ghc-api-version.h, test/data/plugin/KnownNat.hs, test/data/plugin/RecordDot.hs, test/data/plugin/cabal.project, test/data/plugin/plugin.cabal, test/exe/Main.hs
I fixed a couple of test failures in Cabal, Mac OS and GHC 8.10.1 while trying to set up a comprehensive Github CI:
https://github.com/pepeiborra/ghcide/runs/1371409200
Unfortunately I ran out of time before achieving a complete success, but here are the fixes.
=> Test fixes

.github/workflows/test.yml, ghcide.cabal
* To ensure we get the desired version
=> Bump up implicit-hie-cradle lower bound

.github/workflows/nix.yml, README.md, nix/default.nix, nix/sources.json, nix/sources.nix, shell.nix
=> Add a GitHub action for the Nix build

nix/default.nix, nix/sources.json, shell.nix
=> [nix] use gitignore.nix

src/Development/IDE/Plugin/Completions.hs, test/exe/Main.hs
=> Ignore import list while producing completions

src/Development/IDE/Core/Service.hs, src/Development/IDE/Core/Shake.hs, src/Development/IDE/Plugin/Completions.hs, src/Development/IDE/Plugin/Completions/Logic.hs
Fixing a wart that came up during #900
=> Return completion snippets only when client supports it

src/Development/IDE/GHC/Error.hs, test/exe/Main.hs
=> Qualified error messages

session-loader/Development/IDE/Session.hs
Not just the hidir but also the hiedir and the odir
=> Add support for customizing the hidir location

.azure/windows-stack.yml, azure-pipelines.yml, stack-windows.yaml
I finally figured this puzzle out.
=> Rescue stack windows build

src/Development/IDE/Plugin/Completions/Logic.hs
Addresses https://github.com/haskell/haskell-language-server/issues/682
=> Strip prefixes from labels
